(()=>{
  'use strict';
  const KEY='nyx.codeTutorials.v1';
  const lessons={
    javascript:{name:'JavaScript',items:[['Start with values','Values let your program remember information. Use const for a value that should not change.','const learner = "Nyx student";\nconsole.log(`Hello, ${learner}!`);'],['Make a choice','An if statement lets your code choose what to do next.','const finished = true;\nif (finished) console.log("Nice work!");'],['Use a function','Functions keep a useful action in one clear place.','function greet(name) {\n  return `Hello, ${name}!`;\n}\nconsole.log(greet("friend"));']]},
    python:{name:'Python',items:[['Start with variables','Python uses names to hold values you will use again.','learner = "Nyx student"\nprint(f"Hello, {learner}!")'],['Make a choice','Indent the work that should happen when a condition is true.','finished = True\nif finished:\n    print("Nice work!")'],['Use a function','Functions make your idea easy to reuse.','def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("friend"))']]},
    html:{name:'HTML',items:[['Build a page','HTML gives a page its meaningful structure.','<main>\n  <h1>Hello, Nyx</h1>\n  <p>My first page.</p>\n</main>'],['Add a link','An anchor connects your page to another place.','<a href="https://nyxlearning.org">Visit Nyx</a>'],['Group related content','Use sections when a part of the page has its own purpose.','<section>\n  <h2>About me</h2>\n  <p>I am learning HTML.</p>\n</section>']]},
    css:{name:'CSS',items:[['Style a page','CSS changes how HTML looks. A rule has a selector and declarations.','body {\n  font-family: system-ui;\n  color: #172033;\n}'],['Use spacing','Padding adds room inside an element. Margin adds room around it.','.card {\n  padding: 1rem;\n  margin: 1rem;\n}'],['Use a layout','Grid is a clean way to arrange content.','.cards {\n  display: grid;\n  gap: 1rem;\n}']]},
    java:{name:'Java',items:[['Print a message','Java starts execution in a main method.','public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, Nyx!");\n  }\n}'],['Use a variable','Give data a type and a useful name.','String learner = "Nyx student";\nSystem.out.println(learner);'],['Use a method','Methods package work you want to do again.','static String greet(String name) {\n  return "Hello, " + name;\n}']]},
    cpp:{name:'C++',items:[['Print a message','Include iostream to use standard output.','#include <iostream>\n\nint main() {\n  std::cout << "Hello, Nyx!\\n";\n}'],['Use a variable','C++ values have types.','std::string learner = "Nyx student";\nstd::cout << learner;'],['Use a function','Functions can return a value to the caller.','std::string greet(std::string name) {\n  return "Hello, " + name;\n}']]},
    sql:{name:'SQL',items:[['Read rows','SELECT chooses the data you want to see.','SELECT name, completed_projects\nFROM learners;'],['Filter rows','WHERE keeps only rows that match a condition.','SELECT name\nFROM learners\nWHERE completed_projects >= 1;'],['Order results','ORDER BY puts results in a useful order.','SELECT name, completed_projects\nFROM learners\nORDER BY completed_projects DESC;']]}
  };
  const refs={list:document.querySelector('[data-course-list]'),label:document.querySelector('[data-course-label]'),title:document.querySelector('[data-lesson-title]'),progress:document.querySelector('[data-progress-label]'),copy:document.querySelector('[data-lesson-copy]'),example:document.querySelector('[data-example-code]'),practice:document.querySelector('[data-practice-code]'),output:document.querySelector('[data-practice-output]'),runner:document.querySelector('[data-practice-runner]'),save:document.querySelector('[data-save-state]'),account:document.querySelector('[data-account-note]')};
  let state=read();let saveTimer=0;
  function read(){try{return {...JSON.parse(localStorage.getItem(KEY)||'{}'),course:'javascript',lesson:0,completed:{}}}catch{return {course:'javascript',lesson:0,completed:{}}}}
  function write(){try{localStorage.setItem(KEY,JSON.stringify(state));refs.save.textContent='Saved on this device'}catch{refs.save.textContent='Could not save locally'};clearTimeout(saveTimer);saveTimer=setTimeout(saveAccount,650)}
  function lesson(){return lessons[state.course].items[state.lesson]}
  function courseFinished(id){return lessons[id].items.filter((_,index)=>state.completed[`${id}:${index}`]).length}
  function renderList(){refs.list.replaceChildren();Object.entries(lessons).forEach(([id,course])=>{const button=document.createElement('button');button.type='button';button.className=id===state.course?'active':'';button.innerHTML=`<strong>${course.name}</strong><small>${courseFinished(id)} of ${course.items.length} finished</small>`;button.addEventListener('click',()=>{state.course=id;state.lesson=0;render();write()});refs.list.append(button)})}
  function render(){const [title,copy,example]=lesson();refs.label.textContent=lessons[state.course].name;refs.title.textContent=title;refs.copy.replaceChildren();copy.split('\n').filter(Boolean).forEach(text=>{const p=document.createElement('p');p.textContent=text;refs.copy.append(p)});refs.example.textContent=example;refs.practice.value=state.drafts?.[`${state.course}:${state.lesson}`]||example;refs.progress.textContent=`${courseFinished(state.course)} of ${lessons[state.course].items.length} finished`;renderList()}
  function practice(){const source=refs.practice.value.trim();if(!source){refs.output.textContent='Write a small example first.';return}if(state.course==='javascript'){refs.output.textContent='Running JavaScript…';const safe=source.replace(/<\/script/gi,'<\\/script');refs.runner.srcdoc=`<!doctype html><script>const send=(kind,text)=>parent.postMessage({type:'nyx:tutorial-run',kind,text:String(text)},'*');console.log=(...values)=>send('log',values.join(' '));try{${safe};send('done','')}catch(error){send('error',error.message)}<\/script>`}else if(state.course==='html'){refs.output.textContent='HTML saved. Open Code Sandbox to preview it in a browser.'}else if(state.course==='css'){refs.output.textContent='CSS saved. Try it in Code Sandbox with a small HTML page.'}else refs.output.textContent=`${lessons[state.course].name} example saved. Run this language in its usual environment when you are ready.`}
  async function token(){if(parent===window)return '';const requestId=`tutorials-${Date.now()}-${Math.random().toString(36).slice(2)}`;return new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;clearTimeout(timer);removeEventListener('message',receive);resolve(String(value||''))};const receive=event=>{if(event.source===parent&&event.origin===location.origin&&event.data?.type==='nyx:account-token-response'&&event.data.requestId===requestId)finish(event.data.token)};const timer=setTimeout(()=>finish(''),2200);addEventListener('message',receive);parent.postMessage({type:'nyx:account-token-request',requestId},location.origin)})}
  async function saveAccount(){const value=await token();if(!value)return;try{const response=await fetch('/api/account/cloud-games/code-tutorials',{method:'PUT',headers:{'content-type':'application/json',Authorization:`Bearer ${value}`},body:JSON.stringify({storage:{progress:JSON.stringify(state)}})});if(response.ok){refs.save.textContent='Progress saved to your account';refs.account.textContent='Your lesson progress is saved to this account.'}}catch{}}
  async function loadAccount(){const value=await token();if(!value)return;try{const response=await fetch('/api/account/cloud-games/code-tutorials',{headers:{Authorization:`Bearer ${value}`}});const data=await response.json();const saved=JSON.parse(data?.storage?.progress||'null');if(saved&&typeof saved==='object'){state={...state,...saved,completed:{...state.completed,...saved.completed}};refs.account.textContent='Your lesson progress is saved to this account.';render()}}catch{}}
  document.querySelector('[data-copy-example]').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(refs.example.textContent);refs.output.textContent='Example copied.'}catch{refs.output.textContent='Select and copy the example from the lesson.'}});document.querySelector('[data-run-practice]').addEventListener('click',practice);document.querySelector('[data-finish-lesson]').addEventListener('click',()=>{state.completed[`${state.course}:${state.lesson}`]=true;refs.output.textContent='Lesson complete. Keep going when you are ready.';write();render()});document.querySelector('[data-previous]').addEventListener('click',()=>{state.lesson=Math.max(0,state.lesson-1);render();write()});document.querySelector('[data-next]').addEventListener('click',()=>{state.lesson=(state.lesson+1)%lessons[state.course].items.length;render();write()});refs.practice.addEventListener('input',()=>{state.drafts={...(state.drafts||{}),[`${state.course}:${state.lesson}`]:refs.practice.value};write()});addEventListener('message',event=>{if(event.source!==refs.runner.contentWindow||event.data?.type!=='nyx:tutorial-run')return;if(event.data.kind==='log')refs.output.textContent=(refs.output.textContent==='Running JavaScript…'?'':`${refs.output.textContent}\n`)+event.data.text;if(event.data.kind==='error')refs.output.textContent=`Check your JavaScript: ${event.data.text}`;if(event.data.kind==='done'&&refs.output.textContent==='Running JavaScript…')refs.output.textContent='JavaScript ran without console output.'});function theme(){try{const value=localStorage.getItem('nyx.theme');if(['ruby','emerald','sakura','fresh'].includes(value))document.body.classList.add(`theme-${value}`)}catch{}}addEventListener('storage',event=>{if(event.key==='nyx.theme')location.reload()});theme();render();void loadAccount();
})();
