import {createRequire} from 'node:module';
import {mkdtempSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const {_electron} = require('../../node_modules/playwright-core');
const folder = path.resolve(import.meta.dirname, '..');
const data = mkdtempSync(path.join(tmpdir(), 'nook-ui-'));
const project = path.join(data, 'project'); mkdirSync(project);
writeFileSync(path.join(project, 'hello.txt'), 'before');
const env = {...process.env, NOOK_TEST_DATA: path.join(data, 'profile')}; delete env.ELECTRON_RUN_AS_NODE;
const executablePath = process.env.NOOK_INSTALLED_EXE || require('electron');
const app = await _electron.launch({executablePath, args: process.env.NOOK_INSTALLED_EXE ? ['--user-data-dir='+path.join(data,'installed-profile')] : [folder], env, timeout: 45000});
try {
  const page = await app.firstWindow(); await page.waitForSelector('#version');
  await page.waitForFunction(() => document.getElementById('version').textContent.includes('Windows'));
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined');
  await app.evaluate(({dialog}, project) => { dialog.showOpenDialog = async () => ({canceled: false, filePaths: [project]}); }, project);
  await page.getByRole('button', {name: 'Settings', exact: true}).click();
  await page.getByRole('button', {name: 'Choose project folder', exact: true}).click();
  await page.locator('#selectedRoot').filter({hasText: project}).waitFor();
  await page.locator('#level').selectOption('3');
  const grantWindow = app.waitForEvent('window'); await page.getByRole('button', {name: 'Review permissions', exact: true}).click();
  const grant = await grantWindow; await grant.locator('#allow').click();
  await page.waitForFunction(() => document.getElementById('scope').textContent.startsWith('Project access'));
  await page.getByRole('button', {name: 'Files', exact: true}).click(); await page.getByRole('button', {name: 'Refresh', exact: true}).click();
  await page.getByRole('button', {name: 'hello.txt', exact: true}).click(); assert.equal(await page.locator('#editor').inputValue(), 'before');
  await page.locator('#editor').fill('after');
  const writeWindow = app.waitForEvent('window'); await page.getByRole('button', {name: 'Review & save', exact: true}).click();
  const review = await writeWindow; await review.locator('#detail').filter({hasText: 'after'}).waitFor(); await review.locator('#allow').click();
  await page.getByRole('button', {name: 'Undo this edit', exact: true}).waitFor(); assert.equal(readFileSync(path.join(project, 'hello.txt'), 'utf8'), 'after');
  const undoWindow = app.waitForEvent('window'); await page.getByRole('button', {name: 'Undo this edit', exact: true}).click(); await (await undoWindow).locator('#allow').click();
  await page.waitForFunction(() => document.getElementById('editor').value === 'before');
  await page.getByRole('button', {name: 'Terminal', exact: true}).click(); await page.locator('#command').fill('Write-Output nook-installed-test');
  const commandWindow = app.waitForEvent('window'); await page.getByRole('button', {name: 'Review & run', exact: true}).click(); await (await commandWindow).locator('#allow').click();
  await page.waitForFunction(() => document.getElementById('terminalOutput').textContent.includes('Exit: 0'));
  assert.match(await page.locator('#terminalOutput').textContent(), /nook-installed-test/);
  await page.locator('#command').fill('Start-Sleep -Seconds 30');
  const denyWindow = app.waitForEvent('window'); await page.getByRole('button', {name: 'Review & run', exact: true}).click(); await (await denyWindow).locator('#deny').click();
  await page.locator('#error').filter({hasText: 'declined'}).waitFor();
  await page.getByRole('button', {name: 'Settings', exact: true}).click(); await page.getByRole('button', {name: 'Revoke now', exact: true}).click();
  await page.waitForFunction(() => document.getElementById('scope').textContent.startsWith('Access paused'));
  await page.getByRole('button', {name: 'Files', exact: true}).click();
  const copyReview=app.waitForEvent('window');await page.locator('#createTest').click();await(await copyReview).locator('#allow').click();
  await page.locator('#testWorkspaceStatus').filter({hasText:'Test copy:'}).waitFor();
  const copyStatus=await page.evaluate(()=>window.nook.invoke('status'));
  await page.getByRole('button',{name:'Terminal',exact:true}).click();await page.locator('#command').fill("[IO.File]::WriteAllText('generated.txt','test copy result'); Write-Output copy-ok");
  const copyCommand=app.waitForEvent('window');await page.getByRole('button',{name:'Review & run',exact:true}).click();await(await copyCommand).locator('#allow').click();
  await page.waitForFunction(()=>document.getElementById('terminalOutput').textContent.includes('Exit: 0'));
  assert.equal(readFileSync(path.join(copyStatus.testWorkspace.root,'generated.txt'),'utf8'),'test copy result');
  assert.equal(require('node:fs').existsSync(path.join(project,'generated.txt')),false);
  await page.getByRole('button',{name:'Files',exact:true}).click();await page.locator('#reviewTest').click();
  const apply=app.waitForEvent('window');await page.getByRole('button',{name:'Review & apply',exact:true}).click();await(await apply).locator('#allow').click();
  await page.locator('#testChanges').filter({hasText:'No changes'}).waitFor();assert.equal(readFileSync(path.join(project,'generated.txt'),'utf8'),'test copy result');
  await page.screenshot({path: path.join(data, 'desktop.png')});
  const secure = await app.evaluate(({BrowserWindow}) => { const prefs = BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences(); return {sandbox: prefs.sandbox, nodeIntegration: prefs.nodeIntegration, contextIsolation: prefs.contextIsolation}; });
  assert.deepEqual(secure, {sandbox: true, nodeIntegration: false, contextIsolation: true});
  console.log('PASS ' + (process.env.NOOK_INSTALLED_EXE ? 'installed' : 'development') + ' desktop startup, isolated renderer, native approvals, real file save/undo, command execution/denial and revocation');
  console.log('Screenshot: ' + path.join(data, 'desktop.png'));
} finally { await app.close(); }
