import {measureFetch} from './traffic.mjs';
export function setupDropEmbed({user=()=>null,signup=()=>{}}={}){
window.fetch=measureFetch(window.fetch.bind(window),(kind,bytes)=>parent.postMessage({type:'drop:activity',kind,bytes},location.origin));
document.documentElement.classList.add('drop-ai');document.documentElement.dataset.theme='dark';document.title='Drop AI';document.getElementById('accountKeyLabel').value='Drop';
const link=document.createElement('link');link.rel='stylesheet';link.href='/apps/drop/ai.css';document.head.append(link);
const brand=document.querySelector('.brand');brand.textContent='AI chats';brand.removeAttribute('href');brand.setAttribute('aria-label','Drop AI chats');document.getElementById('useCreatedKey').textContent='Use in Drop';document.querySelector('link[rel="icon"]').href='/apps/drop/logo.svg';
document.querySelector('.footnote').textContent='';
const observer=new MutationObserver(()=>{if(document.documentElement.dataset.theme!=='dark')document.documentElement.dataset.theme='dark';});observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='drop:command')return;const action=event.data.action;if(action==='signup')signup();if(action==='keys')document.getElementById('apiKeys').click();if(action==='signin'&&document.getElementById('account').textContent.includes('Sign in'))document.getElementById('account').click();if(action==='signout'&&document.getElementById('account').textContent.includes('Sign out'))document.getElementById('account').click();});
addEventListener('message',async event=>{if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='drop:game-account')return;const request=event.data.request;if(!['nyx:cloud-game-load','nyx:cloud-game-save','nyx:account-token-request'].includes(request?.type))return;const result={type:request.type==='nyx:account-token-request'?'nyx:account-token-response':'nyx:cloud-game-result',requestId:request.requestId};try{const token=await user()?.getIdToken();if(request.type==='nyx:account-token-request')result.token=token||'';else if(!token)result.storage={};else{const save=request.type==='nyx:cloud-game-save';const response=await fetch('/api/account/cloud-games/'+encodeURIComponent(String(request.gameKey||'')),{method:save?'PUT':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(save?{body:JSON.stringify({storage:request.storage,removed:request.removed})}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Cloud save unavailable.');Object.assign(result,data);}}catch(error){result.error=error.message;}parent.postMessage({type:'drop:game-result',result},location.origin);});
addEventListener('message',async event=>{if(event.origin!==location.origin||event.source!==parent||event.data?.type!=='drop:session-token')return;let token='';try{token=await user()?.getIdToken()||'';}catch{}parent.postMessage({type:'drop:session-token-result',requestId:event.data.requestId,token},location.origin);});
const toggle=document.createElement('button');toggle.id='dropHistory';toggle.type='button';toggle.title='Chat history';toggle.setAttribute('aria-label','Chat history');toggle.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v12H9l-5 4z"/></svg>';document.querySelector('.chat-toolbar').prepend(toggle);toggle.onclick=()=>{document.body.classList.remove('sidebar-collapsed');document.body.classList.toggle('history-open');};
document.getElementById('collapseChats').onclick=()=>document.body.classList.remove('history-open');parent.postMessage({type:'drop:ready'},location.origin);
}
