import {setupDropPresence} from './presence.mjs';
import {browse,control,closeBrowser,currentWebsiteUrl,testRelay} from '../tutsi/proxy.mjs';
import {websiteAddress} from '../tutsi/navigation.mjs';
import {protectionSandbox,installShellPopupProtection,installGameProtectionHost} from '../tutsi/protections.mjs';
import {trafficMeter} from './traffic.mjs';
const $=id=>document.getElementById(id);
const paths={game:'M8 9h8a5 5 0 0 1 4.6 6.9l-.8 2a2 2 0 0 1-3.2.8L14.8 17H9.2l-1.8 1.7a2 2 0 0 1-3.2-.8l-.8-2A5 5 0 0 1 8 9z M8 12v4M6 14h4M16.5 13.2h.1M18.2 15h.1',bookmark:'M6 3h12v18l-6-4-6 4z',pin:'M8 3h8l-1 6 4 4v2H5v-2l4-4z M12 15v6',panel:'M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z M9 3v18',plus:'M12 5v14 M5 12h14',home:'m3 10 9-7 9 7v11h-6v-7H9v7H3z',ai:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z M20 2v4 M18 4h4 M3 18v4 M1 20h4',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',account:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-2a8 8 0 0 1 16 0v2',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',enter:'M20 5v9H4m5-5-5 5 5 5',close:'m6 6 12 12 M18 6 6 18',back:'m14 5-7 7 7 7',forward:'m10 5 7 7-7 7',reload:'M20 11a8 8 0 1 0-2 6 M20 4v7h-7',file:'M6 3h8l4 4v14H6z M14 3v5h5',video:'M3 5h18v14H3z m7 4 6 3-6 3z',github:'M9 19c-4 1-4-2-6-2 m12 5v-4a4 4 0 0 0-1-3c3 0 6-1 6-6a5 5 0 0 0-1-3 5 5 0 0 0 0-3s-2 0-4 2a13 13 0 0 0-6 0C7 3 5 3 5 3a5 5 0 0 0 0 3 5 5 0 0 0-1 3c0 5 3 6 6 6a4 4 0 0 0-1 3v4',key:'M21 7a5 5 0 1 1-10 0 5 5 0 0 1 10 0 M12 11 3 20h4v-4h4v-4',chevron:'m9 5 7 7-7 7'};
const icon=name=>name==='settings'?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>':name==='ai'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 3 2.1 6.9L19 12l-6.9 2.1L10 21l-2.1-6.9L1 12l6.9-2.1L10 3Z"/><path d="M20 2v6m-3-3h6"/><rect x="2" y="19" width="3" height="3" rx="1"/></svg>':name==='panel'?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+paths[name]+'"/></svg>';
document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML=icon(n.dataset.icon));
const openCloakWindow=window.open.bind(window);
const defaults={engine:'duckduckgo',restore:true,popupBlock:true,adBlock:true,downloadBlock:true,transport:'epoxy',autoRelay:true,blocker:'auto'};
let saved={};try{saved=JSON.parse(localStorage.getItem('drop.settings')||'{}');}catch{}
const settings={...defaults,closePrevention:saved.closePrevention===true,engine:['duckduckgo','google','bing'].includes(saved.engine)?saved.engine:defaults.engine,restore:saved.restore!==false,popupBlock:saved.popupBlock!==false,adBlock:saved.adBlock!==false};
settings.connection=['auto','bridge','direct'].includes(saved.connection)?saved.connection:'auto';
function configureConnection(){settings.httpBridge=settings.connection!=='direct';settings.autoRelay=settings.connection!=='bridge';}
configureConnection();
const meter=trafficMeter();settings.onTraffic=(direction,bytes)=>meter.add(direction,bytes);
installShellPopupProtection(()=>settings,()=>view==='browser'||view==='games');
installGameProtectionHost(()=>settings,()=>[$('gamesFrame')]);
let tabs=[],active=null,view='home',noticeTimer,aiReady=false,pendingAi=[],signedIn=false;
function notice(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6500);}
function saveSettings(){try{localStorage.setItem('drop.settings',JSON.stringify(settings));}catch{notice('Browser storage is unavailable.');}}
function saveTabs(){try{if(settings.restore)localStorage.setItem('drop.tabs',JSON.stringify(tabs.map(({url,title,pinned})=>({url,title,pinned:!!pinned}))));else localStorage.removeItem('drop.tabs');}catch{}}
function setView(next){view=next;document.body.dataset.view=next;for(const name of ['home','browser','ai','games','tube','bookmarks'])$(name).hidden=name!==next;$('homeNav').toggleAttribute('aria-current',next==='home');$('homeNav').setAttribute('aria-current',next==='home'?'page':'false');$('aiNav').setAttribute('aria-current',next==='ai'?'page':'false');if(next==='home'){$('query').value='';$('query').focus();}if(next==='ai')ensureAi();if(next==='games'&&!$('gamesFrame').getAttribute('src')){$('gamesFrame').src='/apps/drop/games.html';ensureAi();}if(next==='tube'&&!$('tubeFrame').getAttribute('src')){$('tubeFrame').src='/apps/drop/tube.html';ensureAi();}if(next!=='tube'&&$('tubeFrame').contentWindow)$('tubeFrame').contentWindow.postMessage({type:'drop:tube-pause'},location.origin);if(next==='bookmarks')renderBookmarks();for(const name of ['games','tube','bookmarks'])$(name+'Nav').setAttribute('aria-current',next===name?'page':'false');renderTabs();}
function renderTabs(){tabs.sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned));syncPageActions();$('tabCount').textContent=tabs.length;$('tabs').replaceChildren(...tabs.map(tab=>{const row=document.createElement('div');row.className='tab'+(tab.pinned?' pinned':'');row.setAttribute('role','tab');row.setAttribute('aria-selected',String(view==='browser'&&active===tab));const open=document.createElement('button');open.innerHTML=icon(tab.pinned?'pin':'file');const label=document.createElement('span');label.className='label';label.textContent=tab.title||new URL(tab.url).hostname;open.append(label);open.title=label.textContent;open.onclick=()=>activate(tab);const close=document.createElement('button');close.className='icon close-tab';close.innerHTML=icon('close');close.setAttribute('aria-label','Close '+label.textContent);close.onclick=()=>remove(tab);const pin=document.createElement('button');pin.className='icon pin-tab';pin.innerHTML=icon('pin');pin.setAttribute('aria-label',(tab.pinned?'Unpin ':'Pin ')+label.textContent);pin.setAttribute('aria-pressed',String(!!tab.pinned));pin.onclick=()=>togglePin(tab);row.append(open,pin,close);return row;}));}
function activate(tab){active=tab;setView('browser');for(const item of tabs)if(item.frame)item.frame.hidden=item!==tab;$('address').value=tab.url;$('loading').textContent=tab.loading?'Loading...':'';showBrowseError(tab.error);if(!tab.frame)void navigate(tab,tab.url);}
function remove(tab){clearTimeout(tab.loadTimer);const i=tabs.indexOf(tab);tabs=tabs.filter(t=>t!==tab);if(tab.frame){closeBrowser(tab.frame);tab.frame.remove();}if(active===tab){active=null;if(tabs.length)activate(tabs[Math.max(0,i-1)]);else setView('home');}renderTabs();saveTabs();}
function newTab(url){if(tabs.length>=20){notice('Close a tab before opening another.');return;}const tab={id:crypto.randomUUID(),url,title:new URL(url).hostname,version:0};tabs.push(tab);activate(tab);saveTabs();}
async function navigate(tab,url){const version=++tab.version;tab.url=url;tab.title=new URL(url).hostname;tab.loading=true;tab.error='';clearTimeout(tab.loadTimer);if(active===tab)showBrowseError('');tab.loadTimer=setTimeout(()=>failNavigation(tab,version,'The page took too long to respond. Check your connection or try again.'),45000);if(!tab.frame){const frame=document.createElement('iframe');frame.title=tab.title;frame.setAttribute('sandbox',protectionSandbox(settings));frame.setAttribute('allow','fullscreen; autoplay; clipboard-write');frame.referrerPolicy='no-referrer';frame.hidden=active!==tab;tab.frame=frame;$('stage').append(frame);frame.addEventListener('load',()=>{if(!tabs.includes(tab))return;try{if(frame.contentWindow.location.href==='about:blank')return;}catch{}try{const doc=frame.contentDocument;if(doc?.body?.innerText.trim().startsWith('Internal Service Worker Error:')){failNavigation(tab,tab.version,'The browsing connection failed. Try again or check Connection in Settings.');return;}if(doc?.body&&!doc.body.textContent.trim()&&!doc.body.querySelector('*')){failNavigation(tab,tab.version,'The website returned an empty page. Try loading it again.');return;}}catch{}try{const current=currentWebsiteUrl(frame);if(current&&/^https?:/.test(current)){tab.url=current;tab.title=frame.contentDocument?.title||new URL(current).hostname;}}catch{}clearTimeout(tab.loadTimer);tab.loading=false;tab.error='';if(active===tab){showBrowseError('');$('address').value=tab.url;$('loading').textContent='';}renderTabs();saveTabs();});}if(active===tab){$('address').value=url;$('loading').textContent='Loading...';}renderTabs();try{await browse(url,settings,tab.frame);if(version!==tab.version||!tabs.includes(tab))return;saveTabs();}catch(error){if(version!==tab.version||!tabs.includes(tab))return;failNavigation(tab,version,error.message||'Could not open this page. Try again.');}}
$('search').onsubmit=e=>{e.preventDefault();try{newTab(websiteAddress($('query').value,settings.engine));}catch(error){notice(error.message);}};
$('addressForm').onsubmit=e=>{e.preventDefault();if(active)try{void navigate(active,websiteAddress($('address').value,settings.engine));}catch(error){notice(error.message);}};
$('back').onclick=()=>control('back',active?.frame);$('forward').onclick=()=>control('forward',active?.frame);$('reload').onclick=$('retryPage').onclick=()=>{if(active)void navigate(active,currentWebsiteUrl(active.frame)||active.url);};
$('newTab').onclick=$('homeNav').onclick=()=>setView('home');$('aiNav').onclick=()=>setView('ai');$('tubeNav').onclick=()=>setView('tube');$('gamesNav').onclick=()=>setView('games');$('bookmarksNav').onclick=()=>setView('bookmarks');
$('astraNav').onclick=()=>newTab('https://astra-education.top/');
$('shortcuts').onclick=e=>{const button=e.target.closest('[data-url]');if(button){if(button.dataset.url==='https://youtube.com')setView('tube');else newTab(button.dataset.url);}};
function collapse(value){document.body.classList.toggle('collapsed',value);$('collapse').setAttribute('aria-expanded',String(!value));$('collapse').setAttribute('aria-label',value?'Expand sidebar':'Collapse sidebar');$('collapse').title=value?'Expand sidebar':'Collapse sidebar';try{localStorage.setItem('drop.collapsed',String(value));}catch{}}
$('collapse').onclick=()=>collapse(!document.body.classList.contains('collapsed'));try{collapse(matchMedia('(max-width:700px)').matches||localStorage.getItem('drop.collapsed')==='true');}catch{}
$('connectionMode').value=settings.connection;
$('connectionMode').onchange=()=>{settings.connection=$('connectionMode').value;configureConnection();saveSettings();$('connectionStatus').textContent='Ready for next navigation';notice('Connection preference saved. Reload an open page to apply it.');};
$('testConnection').onclick=async()=>{const button=$('testConnection');button.disabled=true;try{await testRelay(settings);}catch(error){$('connectionStatus').textContent='Unavailable';notice(error.message);}finally{button.disabled=false;}};
addEventListener('tutsi:relay-status',({detail})=>{const bridge=detail.url?.includes('/api/tutsi-relay/socket/');$('connectionStatus').textContent=['connected','available','switched'].includes(detail.state)?(bridge?'HTTP bridge connected':'WebSocket connected'):detail.state==='checking'?'Connecting...':'Unavailable';});
// SPA navigation updates history without firing an iframe load event.
setInterval(()=>{if(document.hidden||view!=='browser'||!active?.frame||active.loading)return;const url=currentWebsiteUrl(active.frame);if(!url||!/^https?:/.test(url))return;let title=active.title;try{title=active.frame.contentDocument?.title||new URL(url).hostname;}catch{}if(url===active.url&&title===active.title)return;active.url=url;active.title=title;if(document.activeElement!==$('address'))$('address').value=url;renderTabs();saveTabs();},500);
$('engine').value=settings.engine;$('restore').checked=settings.restore;$('popups').checked=settings.popupBlock;$('ads').checked=settings.adBlock;
$('settingsButton').onclick=()=>$('settings').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
for(const [id,key] of [['engine','engine'],['restore','restore'],['popups','popupBlock'],['ads','adBlock']])$(id).onchange=()=>{settings[key]=id==='engine'?$(id).value:$(id).checked;saveSettings();saveTabs();if(id==='popups'||id==='ads'){for(const t of tabs)if(t.frame)t.frame.setAttribute('sandbox',protectionSandbox(settings));import('../tutsi/proxy.mjs').then(m=>m.updateProtectionPolicy(settings));}};
$('clearTabs').onclick=()=>{for(const tab of [...tabs])remove(tab);try{localStorage.removeItem('drop.tabs');}catch{}notice('Tabs cleared.');};
function ensureAi(){if(!$('aiFrame').getAttribute('src'))$('aiFrame').src='/apps/agents/?shell=drop';}
function aiCommand(action){ensureAi();if(aiReady)$('aiFrame').contentWindow.postMessage({type:'drop:command',action},location.origin);else pendingAi.push(action);}
$('keys').onclick=$('accountKeys').onclick=()=>{$('settings').close();$('accountMenu').close();setView('ai');aiCommand('keys');};
$('createAccount').onclick=()=>{$('accountMenu').close();setView('ai');aiCommand('signup');};
$('profile').onclick=()=>{$('accountMenu').showModal();ensureAi();};$('accountAction').onclick=()=>{$('accountMenu').close();setView('ai');aiCommand(signedIn?'signout':'signin');};
addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==$('aiFrame').contentWindow)return;const data=event.data;if(data?.type==='drop:activity'&&['start','end','up','down'].includes(data.kind)){meter.add(data.kind,data.bytes);return;}if(data?.type==='drop:ready'){aiReady=true;for(const action of pendingAi)aiCommand(action);pendingAi=[];}if(data?.type==='drop:account'){signedIn=data.signedIn===true;dropProfile={uid:data.uid||'',signedIn,displayName:data.name||'Drop account',avatarUrl:data.avatarUrl||''};$('createAccount').hidden=signedIn;if(tubeProfileRequest)$('tubeFrame').contentWindow?.postMessage({type:'nyx:nyxtube-profile',requestId:tubeProfileRequest,profile:dropProfile},location.origin);$('accountName').textContent=data.name||'Account';$('accountAction').textContent=signedIn?'Sign out':'Sign in';$('profile').title=signedIn?data.name||'Account':'Sign in';}});
const formatBytes=bytes=>bytes>=1e9?(bytes/1e9).toFixed(2)+' GB':bytes>=1e6?(bytes/1e6).toFixed(2)+' MB':bytes>=1e3?(bytes/1e3).toFixed(1)+' KB':bytes+' B';
setInterval(()=>{
 const sample=meter.sample();$('speed').textContent=sample.mbps.toFixed(2)+' Mbps';
 const values={traffic:'Traffic: '+sample.download.toFixed(2)+' down / '+sample.upload.toFixed(2)+' up Mbps',requests:'Requests: '+sample.rps.toFixed(1)+'/s / '+sample.totalRequests+' total',data:'Data: '+formatBytes(sample.totalBytes)+' transferred',processing:'Processing: '+Math.round(sample.processing)+'% active time / '+sample.active+' in flight'};
 $('transferDetail').replaceChildren(...Object.entries(values).map(([key,text])=>{const row=document.createElement('div');row.dataset.series=key;row.textContent=text;return row;}));
 $('traffic').setAttribute('aria-label','Activity. '+Object.values(values).join('. '));
 for(const [key,samples]of Object.entries(sample.history)){const max=key==='processing'?100:Math.max(key==='traffic'?.1:1,...samples);$('graph').querySelector('[data-series='+key+']').setAttribute('d',samples.map((value,i)=>(i?'L':'M')+(i*90/(samples.length-1)).toFixed(1)+' '+(26-value/max*23).toFixed(1)).join(' '));}
},1000);
addEventListener('keydown',e=>{if(e.altKey&&e.key==='n'){e.preventDefault();setView('home');}if(e.altKey&&e.key==='w'&&view==='browser'&&active){e.preventDefault();remove(active);}if(e.altKey&&/^[1-9]$/.test(e.key)&&tabs[Number(e.key)-1]){e.preventDefault();activate(tabs[Number(e.key)-1]);}});
if(settings.restore)try{const stored=JSON.parse(localStorage.getItem('drop.tabs')||'[]');if(Array.isArray(stored))tabs=stored.slice(0,20).filter(t=>typeof t.url==='string'&&/^https?:\/\//.test(t.url)).map(t=>({id:crypto.randomUUID(),url:new URL(t.url).href,title:String(t.title||new URL(t.url).hostname).slice(0,100),pinned:t.pinned===true,version:0}));}catch{}

function showBrowseError(message){$('browseError').hidden=!message;$('browseErrorText').textContent=message||'';}
function failNavigation(tab,version,message){if(!tabs.includes(tab)||tab.version!==version)return;clearTimeout(tab.loadTimer);tab.loading=false;tab.error=message;if(active===tab){$('loading').textContent='';showBrowseError(message);}}
function togglePin(tab){tab.pinned=!tab.pinned;renderTabs();saveTabs();}
let bookmarks=[];try{const saved=JSON.parse(localStorage.getItem('drop.bookmarks')||'[]');if(Array.isArray(saved))bookmarks=saved.filter(b=>typeof b.url==='string'&&/^https?:\/\//.test(b.url)).map(b=>({url:new URL(b.url).href,title:String(b.title||b.url).slice(0,200)}));}catch{}
function persistBookmarks(){try{localStorage.setItem('drop.bookmarks',JSON.stringify(bookmarks));}catch{notice('Bookmarks could not be saved. Browser storage may be full.');}syncPageActions();renderBookmarks();}
function syncPageActions(){const saved=!!active&&bookmarks.some(b=>b.url===active.url);for(const [id,on,label]of [['bookmarkPage',saved,saved?'Remove bookmark':'Bookmark page'],['pinPage',!!active?.pinned,active?.pinned?'Unpin tab':'Pin tab']]){$(id).setAttribute('aria-pressed',String(on));$(id).setAttribute('aria-label',label);$(id).title=label;}}
$('bookmarkPage').onclick=()=>{if(!active)return;const i=bookmarks.findIndex(b=>b.url===active.url);if(i>=0)bookmarks.splice(i,1);else bookmarks.unshift({url:active.url,title:active.title});persistBookmarks();};
$('pinPage').onclick=()=>{if(active)togglePin(active);};
function renderBookmarks(){const query=$('bookmarkSearch').value.trim().toLowerCase();const matches=bookmarks.filter(b=>(b.title+' '+b.url).toLowerCase().includes(query));$('bookmarkList').replaceChildren(...matches.map(b=>{const row=document.createElement('div');row.className='bookmark-row';const open=document.createElement('button');open.innerHTML=icon('bookmark');const text=document.createElement('span'),title=document.createElement('strong'),url=document.createElement('small');title.textContent=b.title;url.textContent=b.url;text.append(title,url);open.append(text);open.onclick=()=>newTab(b.url);const remove=document.createElement('button');remove.className='icon';remove.innerHTML=icon('close');remove.setAttribute('aria-label','Remove bookmark '+b.title);remove.onclick=()=>{bookmarks=bookmarks.filter(item=>item!==b);persistBookmarks();};row.append(open,remove);return row;}));$('bookmarkEmpty').hidden=matches.length>0;$('bookmarkEmpty').textContent=bookmarks.length?'No matching bookmarks.':'Save a page with the bookmark icon in the address bar.';}
$('bookmarkSearch').oninput=renderBookmarks;
// Only the trusted library frame can ask the account frame for game persistence.
addEventListener('message',event=>{if(event.origin!==location.origin)return;const data=event.data;if(event.source===$('gamesFrame').contentWindow&&['nyx:cloud-game-load','nyx:cloud-game-save','nyx:account-token-request'].includes(data?.type)){ensureAi();const send=()=> $('aiFrame').contentWindow.postMessage({type:'drop:game-account',request:data},location.origin);if(aiReady)send();else{const timer=setInterval(()=>{if(aiReady){clearInterval(timer);send();}},100);setTimeout(()=>clearInterval(timer),5000);}}if(event.source===$('aiFrame').contentWindow&&data?.type==='drop:game-result')$('gamesFrame').contentWindow?.postMessage(data.result,location.origin);});
setView('home');

let tubeProfileRequest='';
let dropProfile={signedIn:false,displayName:'Drop account'};
addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==$('tubeFrame').contentWindow)return;const data=event.data;if(data?.type==='nyx:nyxtube-profile-request'){tubeProfileRequest=data.requestId;event.source.postMessage({type:'nyx:nyxtube-profile',requestId:data.requestId,profile:dropProfile},location.origin);}if(data?.type==='nyx:nyxtube-open-profile')$('profile').click();});

setupDropPresence({frame:$('aiFrame'),ensureAccount:ensureAi,notice});

function preventDropClose(event){event.preventDefault();event.returnValue='';}
function syncClosePrevention(){removeEventListener('beforeunload',preventDropClose);if(settings.closePrevention)addEventListener('beforeunload',preventDropClose);$('closePrevention').checked=settings.closePrevention;}
$('closePrevention').onchange=()=>{settings.closePrevention=$('closePrevention').checked;saveSettings();syncClosePrevention();};
syncClosePrevention();
addEventListener('storage',event=>{if(event.key!=='drop.settings')return;try{settings.closePrevention=JSON.parse(event.newValue||'{}').closePrevention===true;syncClosePrevention();}catch{}});
$('blankCloak').onclick=()=>{
 try{if(parent!==window&&parent.location.href==='about:blank'){notice('Drop is already open in about:blank.');return;}}catch{}
 const popup=openCloakWindow('about:blank','_blank');
 if(!popup){notice('Allow popups for this site, then try again.');return;}
 try{
  const doc=popup.document;doc.title='New Tab';doc.documentElement.style.cssText='height:100%;background:#202020';doc.body.style.cssText='margin:0;height:100%;overflow:hidden';
  const frame=doc.createElement('iframe');frame.title='Drop';frame.src=location.href;frame.style.cssText='display:block;width:100%;height:100%;border:0';frame.allow='autoplay; fullscreen; gamepad; microphone; display-capture; clipboard-read; clipboard-write';frame.allowFullscreen=true;doc.body.replaceChildren(frame);popup.opener=null;popup.focus();$('settings').close();
 }catch{popup.close();notice('Could not open the about:blank window. Try again.');}
};
