function recentActivity(item){
 const messages=item.messages||[];
 const lastUser=messages.findLastIndex(message=>message.role==='user');
 const text=(lastUser>=0?messages.slice(lastUser).map(message=>message.content).join(' '):item.title).toLowerCase();
 if(/\bgithub\b|github\.com/.test(text))return 'github';
 if(/\b(deploy|deployment|hosting|publish)\b/.test(text))return 'deploy';
 if(/\b(image|photo|picture|screenshot|illustration)\b/.test(text))return 'image';
 if(/\b(search|research|look up|find sources)\b/.test(text))return 'search';
 if(/\b(code|debug|bug|html|css|javascript|python|function)\b/.test(text))return 'code';
 return item.computer?'file':'chat';
}
export function setupChats({open,notice,busy,changed=()=>{}}){
 const list=document.getElementById('chatList'),search=document.getElementById('chatSearch');let uid='',items=[],current='',temporary=false;
 const key=()=> 'agents.chats.v1.'+uid;
 function write(){if(!uid)return;try{localStorage.setItem(key(),JSON.stringify(items));}catch{notice('Chat history could not be saved. Your current chat is still open.');}}
 function render(){document.getElementById('chatCount').textContent=items.length;list.replaceChildren();for(const item of items.filter(item=>[item.title,...item.messages.map(message=>message.content)].join(' ').toLowerCase().includes(search.value.toLowerCase()))){const row=document.createElement('div');row.className='saved-chat';const button=document.createElement('button');button.type='button';const glyph=document.createElement('span');glyph.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v12H9l-5 4z"/></svg>';const label=document.createElement('span');label.className='chat-title';const title=document.createElement('strong');title.textContent=item.title;const date=document.createElement('small');date.textContent=new Date(item.updated||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});label.append(title,date);button.append(glyph,label);button.title=item.title;button.setAttribute('aria-current',String(item.id===current));button.onclick=()=>{if(busy())return;current=item.id;temporary=false;open(structuredClone(item));render();};const remove=document.createElement('button');remove.type='button';remove.setAttribute('aria-label','Delete '+item.title);remove.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 10v7M14 10v7"/></svg>';remove.onclick=()=>{if(busy())return;items=items.filter(entry=>entry.id!==item.id);write();if(current===item.id)fresh(false);render();};row.append(button,remove);list.append(row);}document.getElementById('tempChat').setAttribute('aria-pressed',String(temporary));if(!items.length){const text=document.createElement('p');text.className='muted';text.textContent=uid?'Your chats appear here.':'Sign in to save chats on this browser.';list.append(text);}changed();}
 function resume(id){if(busy())return;const item=items.find(item=>item.id===id);if(!item)return;current=id;temporary=false;open(structuredClone(item));render();}
 function fresh(temp){if(busy())return;current='';temporary=temp;open({messages:[],temporary:temp});render();}
 document.getElementById('sidebarNewChat').onclick=()=>fresh(false);document.getElementById('tempChat').onclick=()=>fresh(true);search.oninput=render;
 return {recent:()=>temporary?[]:items.slice().sort((a,b)=>(b.updated||0)-(a.updated||0)).slice(0,3).map(item=>({id:item.id,title:item.title,computer:item.computer,activity:recentActivity(item)})),resume,bind(user){uid=user||'';items=[];current='';temporary=false;if(uid)try{const data=JSON.parse(localStorage.getItem(key())||'[]');items=Array.isArray(data)?data.filter(item=>item&&typeof item.id==='string'&&typeof item.title==='string'&&Array.isArray(item.messages)&&item.messages.every(m=>['user','assistant'].includes(m.role)&&typeof m.content==='string')).slice(0,50):[];}catch{}open({messages:[]});render();},fresh,temporary:()=>temporary,save(messages,model,computer,effort){if(!uid||temporary||!messages.length)return;if(!current)current=crypto.randomUUID();const entry={id:current,title:messages.find(m=>m.role==='user')?.content.slice(0,60)||'New chat',model,computer,effort,messages:messages.slice(-40).map(m=>({role:m.role,content:m.content.slice(0,24000),model:m.model||'',metadata:{summary:String(m.metadata?.summary||'').slice(0,2400)}})),updated:Date.now()};items=[entry,...items.filter(item=>item.id!==current)].slice(0,50);write();render();}};
}
