import {readResponse} from './response.js';
import {agentInstruction} from './agent-instruction.js';
import {supportsConversationVoice} from './voice-capabilities.js';
export function setupKeys({user,busy,changed,notice,appName='Nook'}){
 const $=id=>document.getElementById(id);let secret='',uid='',version=0,catalog=[],saving=false;
 const kind=()=>secret.startsWith('n_api_')?'account':'openrouter';
 async function account(path,body,method){const token=await user()?.getIdToken();if(!token)throw Error('Sign in first.');return readResponse(await fetch('/api/developer'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'}));}
 function sync(){ $('apiKeys').setAttribute('aria-pressed',String(!!secret));$('keyConnection').textContent=secret?(kind()==='account'?'Using your account API key':'Using your OpenRouter key'):'Using shared access'; }
 function clearReveal(){$('createdKey').value='';$('createdKeyPanel').hidden=true;$('personalKey').value='';}
 async function refresh(){const mine=version;try{const data=await account('/me');if(mine!==version)return;$('createAccountKey').disabled=!!data.key||!data.configured;$('revokeAccountKey').hidden=!data.key;$('accountKeyStatus').textContent=data.key?'Active key: '+data.key.prefix+'...':'No active account API key.';}catch(e){if(mine!==version)return;$('accountKeyStatus').textContent=e.message;$('createAccountKey').disabled=true;}}
 $('apiKeys').onclick=()=>{if(busy())return;sync();$('keyError').textContent='';$('keyDialog').showModal();void refresh();};
 $('closeKeys').onclick=()=>{if(!saving)$('keyDialog').close();};$('keyDialog').addEventListener('cancel',e=>{if(saving)e.preventDefault();});$('keyDialog').addEventListener('close',clearReveal);
 $('personalKeyForm').onsubmit=async e=>{e.preventDefault();if(busy()||saving)return;const value=$('personalKey').value.trim();if(!/^sk-or-[A-Za-z0-9_-]{20,}$/.test(value)&&!/^n_api_[A-Za-z0-9_-]{43}$/.test(value)){$('keyError').textContent='Enter an OpenRouter or account API key.';return;}saving=true;const mine=version;$('usePersonalKey').disabled=true;try{if(value.startsWith('sk-or-'))await readResponse(await fetch('https://openrouter.ai/api/v1/key',{headers:{Authorization:'Bearer '+value},redirect:'error',cache:'no-store'}));if(mine!==version)return;secret=value;version++;sync();$('keyDialog').close();await changed();}catch(error){if(mine===version)$('keyError').textContent=error.message.replaceAll(value,'[key]');}finally{saving=false;$('usePersonalKey').disabled=false;}};
 $('useSharedKey').onclick=async()=>{if(busy()||saving)return;secret='';version++;sync();$('keyDialog').close();await changed();};
 $('createAccountKey').onclick=async()=>{if(saving||busy())return;saving=true;$('createAccountKey').disabled=true;const mine=version;try{const data=await account('/keys',{label:$('accountKeyLabel').value.trim()||appName});if(mine!==version)return;$('createdKey').value=data.key;$('createdKeyPanel').hidden=false;await refresh();}catch(e){if(mine!==version)return;$('keyError').textContent=e.message;await refresh();}finally{saving=false;}};
 $('revokeAccountKey').onclick=async()=>{if(saving||busy())return;saving=true;const mine=version;try{await account('/keys',null,'DELETE');if(mine!==version)return;clearReveal();if(secret&&kind()==='account'){secret='';version++;sync();await changed();}await refresh();}catch(e){if(mine!==version)return;$('keyError').textContent=e.message;}finally{saving=false;}};
 $('copyCreatedKey').onclick=async()=>{try{await navigator.clipboard.writeText($('createdKey').value);notice('Key copied.');}catch{notice('Select the key and copy it manually.');}};
 $('useCreatedKey').onclick=async()=>{if(busy()||saving||!$('createdKey').value)return;secret=$('createdKey').value;version++;sync();$('keyDialog').close();await changed();};
 window.addEventListener('pagehide',()=>{secret='';clearReveal();});
 return {revision:()=>version,active:()=>!!secret,bind(next){if(uid===next)return;uid=next;version++;secret='';catalog=[];clearReveal();$('keyDialog').close();sync();},async models(){if(!secret)return null;const key=secret,mine=version;if(kind()==='account'){const details=await account('/me');if(mine!==version)throw new DOMException('Account changed','AbortError');catalog=(details.models||[]).map(id=>({id,label:id,text:true,inputModalities:['text'],outputModalities:['text']}));return {models:catalog};}const data=await readResponse(await fetch('https://openrouter.ai/api/v1/models',{headers:{Authorization:'Bearer '+key},redirect:'error',cache:'no-store'}));if(mine!==version)throw new DOMException('Account changed','AbortError');catalog=(data.data||[]).map(m=>({id:m.id,label:m.name||m.id,created:m.created,inputModalities:m.architecture?.input_modalities||[],outputModalities:m.architecture?.output_modalities||['text'],text:(m.architecture?.output_modalities||['text']).includes('text'),vision:m.architecture?.input_modalities?.includes('image'),reasoning:m.supported_parameters?.includes('reasoning'),supportedParameters:m.supported_parameters||[]}));return {models:catalog};},async send(body,signal,onProgress){const key=secret,own=kind()==='account',model=catalog.find(m=>m.id===body.model);if(own&&(body.image||body.generateAudio))throw Error('Account API keys support text only. Use an OpenRouter key for images and voice.');const messages=(body.messages||[{role:'user',content:body.message}]).map(m=>({role:m.role,content:m.content}));if(body.task==='computer-agent')messages.unshift({role:'system',content:agentInstruction});if(body.image){const last=messages.at(-1);last.content=[{type:'text',text:last.content},{type:'image_url',image_url:{url:body.image.dataUrl}}];}const payload={model:body.model,messages,max_tokens:own?512:body.task==='computer-agent'?4096:2048,stream:own?false:body.stream!==false};if(model?.reasoning)payload.reasoning={effort:body.reasoningEffort||'medium'};let format;
 if(body.generateAudio){if(!supportsConversationVoice(model))throw Error('Choose a conversational voice model.');format=body.model.startsWith('openai/')?'pcm16':'mp3';payload.stream=true;payload.modalities=['text','audio'];payload.audio={voice:body.voice||'alloy',format};}
 try{const response=await fetch(own?'/api/v1/ai':'https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal,redirect:'error',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await readResponse(response,onProgress,format);return data.choices?{text:data.choices[0]?.message?.content||'',model:data.model,finishReason:data.choices[0]?.finish_reason}:data;}catch(error){if(error.name==='AbortError')throw error;throw Error(key?error.message.replaceAll(key,'[key]'):error.message);}}
 };
}
