const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {Workspace} = require('../src/files.cjs');
const {Broker} = require('../src/broker.cjs');
const {Store} = require('../src/store.cjs');
const {Engine, parse} = require('../src/engine.cjs');
const {Provider, ORIGIN} = require('../src/provider.cjs');
const fixture = () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'nook-test-')); fs.mkdirSync(path.join(root, 'project')); return {root, project: path.join(root, 'project'), backup: path.join(root, 'backup')}; };
test('file tools verify writes, reject escapes, retain backups and refuse conflicting undo', () => {
  const f = fixture(), w = new Workspace(f.project, f.backup);
  const saved = w.write('sample.txt', 'first', null); assert(saved.verified);
  const before = w.read('sample.txt'); assert.equal(before.content, 'first');
  assert.throws(() => w.write('sample.txt', 'bad', null), /changed/);
  const edited = w.write('sample.txt', 'second', before.hash);
  assert.equal(w.read('sample.txt').content, 'second');
  w.undo(edited.id); assert.equal(w.read('sample.txt').content, 'first');
  assert.throws(() => w.undo(edited.id), /newer work/);
  for (const target of ['../private', 'C:/private', 'sample.txt:secret', '.env', '.ssh/key', 'CON', 'sample.txt.', 'nested/../secret']) assert.throws(() => w.resolve(target, true));
  fs.writeFileSync(path.join(f.root, 'secret.txt'), 'outside');
  fs.linkSync(path.join(f.root, 'secret.txt'), path.join(f.project, 'hard.txt'));
  assert.throws(() => w.read('hard.txt'), /linked/);
  fs.symlinkSync(f.root, path.join(f.project, 'junction'), 'junction');
  assert.throws(() => w.read('junction/secret.txt'), /junction/);
  assert.deepEqual(w.search('first').matches.map(item => item.path), ['sample.txt']);
});
test('permission levels, expiry, revocation during approval and elevation denial fail closed', async () => {
  const f = fixture(); let allow = true, onApprove = () => {};
  const b = new Broker({...f, helper: '', approve: async () => { onApprove(); return allow; }});
  await assert.rejects(b.run('list', {}), /outside/);
  b.grant(f.project, 1); assert.equal((await b.run('list', {})).entries.length, 0);
  await assert.rejects(b.run('write', {path: 'x', content: 'x', expectedHash: null}), /outside/);
  b.grant(f.project, 2); allow = false;
  await assert.rejects(b.run('write', {path: 'x', content: 'x', expectedHash: null}), /declined/);
  assert(!fs.existsSync(path.join(f.project, 'x')));
  allow = true; onApprove = () => b.revoke(); b.grant(f.project, 3);
  await assert.rejects(b.run('command', {command: 'Write-Output should-not-run'}), /permissions changed/);
  onApprove = () => {}; b.grant(f.project, 4); b.expires = 0;
  await assert.rejects(b.run('read', {path: 'x'}), /outside/);
  b.grant(f.project, 4); await assert.rejects(b.run('elevate', {command: 'Write-Output nope'}), /outside/);
  b.grant(f.project, 5); allow = false; await assert.rejects(b.run('elevate', {command: 'Write-Output nope'}), /declined/);
});
test('approved real PowerShell and CMD execute, return exit status, and stop kills ordinary work', async () => {
  const f = fixture(), b = new Broker({...f, helper: '', approve: async () => true}); b.grant(f.project, 3);
  const ps = await b.run('command', {shell: 'powershell', command: "[IO.File]::WriteAllText('command.txt','real'); Write-Output 'powershell-ok'"});
  assert.equal(ps.exitCode, 0); assert.match(ps.stdout, /powershell-ok/); assert.equal(fs.readFileSync(path.join(f.project, 'command.txt'), 'utf8'), 'real');
  const cmd = await b.run('command', {shell: 'cmd', command: 'echo cmd-ok'}); assert.equal(cmd.exitCode, 0); assert.match(cmd.stdout, /cmd-ok/);
  const controller = new AbortController(); setTimeout(() => controller.abort(), 700);
  const stopped = await b.run('command', {command: 'Start-Sleep -Seconds 30'}, controller.signal); assert.equal(stopped.stopped, 'cancelled'); assert(stopped.durationMs < 10000);
});
test('agent executes a multi-step fixture with real writes and verification; malformed/denied tools do not run', async () => {
  const f = fixture(), store = new Store(path.join(f.root, 'tasks.sqlite')), events = [];
  const broker = new Broker({...f, helper: '', approve: async () => true}); broker.grant(f.project, 2);
  const replies = [{message: 'Inspect', tool: 'list', args: {}}, {message: 'Write', tool: 'write', args: {path: 'result.txt', content: 'verified fixture', expectedHash: null}}, {message: 'Verify', tool: 'read', args: {path: 'result.txt'}}, {message: 'File written and verified', done: true}];
  const engine = new Engine({provider: {complete: async () => ({text: JSON.stringify(replies.shift())})}, broker, store, emit: value => events.push(value)});
  assert.equal((await engine.start({prompt: 'Create result', model: 'fixture'})).state, 'completed');
  assert.equal(fs.readFileSync(path.join(f.project, 'result.txt'), 'utf8'), 'verified fixture');
  assert(events.some(e => e.type === 'result' && e.body.result.verified));
  assert.throws(() => parse('{"message":"bad","tool":"eval","args":{}}'), /Unsupported/);
  broker.revoke(); replies.push({message: 'Read', tool: 'list', args: {}});
  assert.equal((await engine.start({prompt: 'Denied', model: 'fixture'})).state, 'failed');
  const pending = store.create('Interrupted'); store.close(); const reopened = new Store(path.join(f.root, 'tasks.sqlite'));
  assert.equal(reopened.tasks().find(t => t.id === pending).state, 'interrupted'); reopened.close();
});
test('provider uses fixed HTTPS, encrypted storage, catalog validation and redirects are disabled', async () => {
  const f = fixture(), calls = [], key = 'n_api_' + 'a'.repeat(43);
  const safeStorage = {isEncryptionAvailable: () => true, encryptString: v => Buffer.from('encrypted:' + v), decryptString: v => v.toString().slice(10)};
  const provider = new Provider({file: path.join(f.root, 'key'), safeStorage, fetcher: async (url, options) => { calls.push({url, options}); return Response.json(url.endsWith('/models') ? {models: [{id: 'fixture/model'}]} : {choices: [{message: {content: '{"message":"ok","done":true}'}, finish_reason: 'stop'}]}); }});
  assert.equal((await provider.save(key))[0].id, 'fixture/model');
  assert.equal((await provider.complete('fixture/model', [], new AbortController().signal)).finishReason, 'stop');
  assert(calls.every(call => call.url.startsWith(ORIGIN + '/api/v1/') && call.options.redirect === 'error'));
  assert(fs.readFileSync(path.join(f.root, 'key'), 'utf8').startsWith('encrypted:'));
  provider.forget(); assert(!fs.existsSync(path.join(f.root, 'key')));
});
