import {sourceFile} from '../scripture/source-layout.mjs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const workspace=await chromium.launch({channel:'msedge',headless:true});
try{
 let replies=0;const longReply='Long reply paragraph.\n'.repeat(1300)+'END OF LONG REPLY';
 const page=await workspace.newPage({viewport:{width:2048,height:1148}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.env.DROP_TEST_DIST)await page.route('http://localhost:6767/**',async route=>{const path=new URL(route.request().url()).pathname;try{const file=resolve('dist','.'+decodeURIComponent(path)+(path.endsWith('/')?'index.html':''));if(!file.startsWith(resolve('dist')+'\\'))throw Error('Invalid path');await route.fulfill({body:await readFile(sourceFile(file)),contentType:({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.woff2':'font/woff2'})[extname(file)]||'application/octet-stream'});}catch{await route.continue();}});
 await page.route('https://www.gstatic.com/firebasejs/**/firebase-app.js',r=>r.fulfill({contentType:'text/javascript',body:'export const getApps=()=>[];export const initializeApp=()=>({});'}));
 await page.route('https://www.gstatic.com/firebasejs/**/firebase-auth.js',r=>r.fulfill({contentType:'text/javascript',body:'const auth={currentUser:{uid:"fixture-user",getIdToken:async()=>"fixture"}};export const getAuth=()=>auth;export const browserLocalPersistence={};export const setPersistence=async()=>{};export const onAuthStateChanged=(a,f)=>f(a.currentUser);export const signOut=async()=>{};'}));
 await page.route('**/api/**',r=>{const url=r.request().url();if(url.includes('auth-config'))return r.fulfill({json:{enabled:true,apiKey:'fixture',projectId:'fixture'}});if(url.endsWith('/models'))return r.fulfill({json:{models:[{id:'anthropic/claude-test',label:'Anthropic: Claude Test',text:true}]}});if(r.request().method()==='POST'){replies++;return r.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({model:'anthropic/claude-test',choices:[{finish_reason:replies===1?'length':'stop',delta:{content:replies>1?longReply:'Hey! What can I help you with today? I can help explore an idea, explain something, or work through a project together.'}}]})+'\n\ndata: [DONE]\n\n'});}return r.fulfill({json:{profile:{handle:'tester'}}});});
 await page.addInitScript(()=>localStorage.setItem('drop.setupComplete','1'));
 await page.goto(process.env.DROP_TEST_URL||'http://localhost:6767/apps/drop/');await page.locator('#aiNav').click();const ai=page.frameLocator('#aiFrame');await ai.locator('#model option[value="anthropic/claude-test"]').waitFor({state:'attached'});await ai.locator('#prompt').fill('Hey');await ai.locator('#send').click();await ai.getByText('Hey! What can I help you with today?',{exact:false}).waitFor({timeout:10000}).catch(async error=>{console.log(await ai.locator('body').innerText());throw error;});
 await ai.locator('#modelTrigger').click();assert.equal(await ai.locator('.ai-company-rail').count(),0);assert.equal(await ai.locator('#modelCompanies button span').last().innerText(),'Anthropic');assert((await ai.locator('#modelMenu').boundingBox()).width<=590);await ai.locator('#modelCompanies button').click();await ai.locator('#modelSearch').fill('Claude');assert.equal(await ai.locator('.ai-model-option').count(),1);await page.screenshot({path:'.codex-artifacts/drop-model-picker.png'});await ai.locator('.ai-model-option').click();
 await ai.getByRole('button',{name:'Continue response'}).waitFor();
 const reply=ai.locator('.message').last();assert((await reply.boundingBox()).width>600);assert((await reply.boundingBox()).height<250);
 assert.equal(await ai.locator('.reply-logo img').evaluate(img=>getComputedStyle(img).filter),'none');assert(await ai.locator('.reply-logo img').evaluate(img=>img.complete&&img.naturalWidth>0));
 await page.waitForFunction(()=>/Requests.*[1-9]\d* total/.test(document.getElementById('transferDetail').textContent));assert.equal(await page.locator('#graph path[data-series]').count(),4);await page.locator('#traffic').hover();await page.screenshot({path:'.codex-artifacts/drop-activity.png'});
 await page.screenshot({path:'.codex-artifacts/drop-ai-fixed.png'});
 await page.setViewportSize({width:390,height:844});if(await page.locator('#collapse').getAttribute('aria-expanded')==='true')await page.locator('#collapse').click();await page.waitForTimeout(350);assert((await reply.boundingBox()).width>200,JSON.stringify(await reply.boundingBox()));assert(await ai.locator('#feed').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await ai.getByRole('button',{name:'Continue response'}).last().click();await ai.locator('.message.assistant').nth(1).waitFor();assert((await ai.locator('.message.assistant').last().innerText()).includes('END OF LONG REPLY'));await ai.locator('#dropHistory').click();await ai.locator('.saved-chat button').first().click();assert((await ai.locator('.message.assistant').last().innerText()).includes('END OF LONG REPLY'));assert(await page.evaluate(()=>localStorage.getItem('agents.chats.v1.fixture-user').includes('END OF LONG REPLY')));
 assert.deepEqual(errors,[]);console.log('PASS Drop AI reply width on desktop/mobile and original company logo colors');
}finally{await workspace.close();}
