(()=>{
  'use strict';
  const STORAGE_KEY='nyx.codeStudio.v1';
  const MAX_CODE_CHARS=24000;
  const languages={
    html:{file:'index.html',help:'Build a small page and see it safely in the preview.',starter:'<!doctype html>\n<html>\n  <head>\n    <style>\n      body { font-family: system-ui; padding: 2rem; color: #172033; }\n      button { padding: .7rem 1rem; border: 0; border-radius: .6rem; background: #4f6ee8; color: white; }\n    </style>\n  </head>\n  <body>\n    <h1>Hello, Nyx</h1>\n    <p>Make this page your own.</p>\n    <button onclick="this.textContent = \'Nice work!\'">Try it</button>\n  </body>\n</html>',run:true},
    css:{file:'styles.css',help:'Write styles and preview them on a small sample card.',starter:'body {\n  margin: 0;\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n  background: #e8eefc;\n  font-family: system-ui;\n}\n\n.card {\n  max-width: 20rem;\n  padding: 2rem;\n  border-radius: 1.25rem;\n  background: white;\n  box-shadow: 0 18px 45px rgba(46, 67, 122, .18);\n}',run:true},
    javascript:{file:'app.js',help:'Run JavaScript in an isolated browser preview.',starter:'const message = document.querySelector("#message");\nconst button = document.querySelector("button");\n\nbutton.addEventListener("click", () => {\n  message.textContent = "You changed the page with JavaScript.";\n});',run:true},
    typescript:{file:'app.ts',help:'TypeScript editor support with AI suggestions. Browser preview needs compiled JavaScript.',starter:'type Student = {\n  name: string;\n  projects: number;\n};\n\nconst student: Student = { name: "Nyx learner", projects: 1 };\nconsole.log(`${student.name} has ${student.projects} project.`);'},
    python:{file:'main.py',help:'Python editor support with AI suggestions. Run it in your usual Python environment.',starter:'def greet(name: str) -> str:\n    return f"Hello, {name}!"\n\nprint(greet("Nyx learner"))'},
    java:{file:'Main.java',help:'Java editor support with AI suggestions. Run it in a Java environment.',starter:'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello, Nyx learner!");\n  }\n}'},
    c:{file:'main.c',help:'C editor support with AI suggestions. Run it in a C compiler.',starter:'#include <stdio.h>\n\nint main(void) {\n  puts("Hello, Nyx learner!");\n  return 0;\n}'},
    cpp:{file:'main.cpp',help:'C++ editor support with AI suggestions. Run it in a C++ compiler.',starter:'#include <iostream>\n\nint main() {\n  std::cout << "Hello, Nyx learner!\\n";\n  return 0;\n}'},
    csharp:{file:'Program.cs',help:'C# editor support with AI suggestions. Run it in a .NET project.',starter:'Console.WriteLine("Hello, Nyx learner!");'},
    go:{file:'main.go',help:'Go editor support with AI suggestions. Run it with the Go toolchain.',starter:'package main\n\nimport "fmt"\n\nfunc main() {\n  fmt.Println("Hello, Nyx learner!")\n}'},
    rust:{file:'main.rs',help:'Rust editor support with AI suggestions. Run it with Cargo or rustc.',starter:'fn main() {\n    println!("Hello, Nyx learner!");\n}'},
    php:{file:'index.php',help:'PHP editor support with AI suggestions. Run it with a PHP server.',starter:'<?php\n$name = "Nyx learner";\necho "Hello, {$name}!";'},
    ruby:{file:'main.rb',help:'Ruby editor support with AI suggestions. Run it with Ruby.',starter:'def greet(name)\n  "Hello, #{name}!"\nend\n\nputs greet("Nyx learner")'},
    sql:{file:'query.sql',help:'SQL editor support with AI suggestions. Connect it to the database you use.',starter:'SELECT student_name, completed_projects\nFROM learners\nWHERE completed_projects >= 1\nORDER BY completed_projects DESC;'},
    json:{file:'data.json',help:'Validate JSON and inspect its formatted result.',starter:'{\n  "project": "Nyx Code Studio",\n  "languages": ["JavaScript", "Python", "Rust"],\n  "ready": true\n}',run:true},
    markdown:{file:'README.md',help:'Write Markdown and see a safe rendered preview.',starter:'# My project\n\nBuild something useful, then write down what it does.\n\n- Clear goal\n- Small next step\n- Test your work',run:true}
  };
  const starters={html:['Landing page','<main><h1>My project</h1><p>A clear place to start.</p></main>'],javascript:['Click counter','let count = 0;\ndocument.querySelector("button").addEventListener("click", () => {\n  count += 1;\n  document.querySelector("#message").textContent = `Clicked ${count} times`;\n});'],python:['Simple list','tasks = ["Plan", "Build", "Test"]\nfor task in tasks:\n    print(f"- {task}")'],json:['Project data','{\n  "name": "My project",\n  "version": 1,\n  "complete": false\n}'],markdown:['Project notes','# Project notes\n\n## Next up\n\n1. Build a small version\n2. Test it\n3. Improve it']};
  const refs={language:document.querySelector('[data-language]'),help:document.querySelector('[data-language-help]'),files:document.querySelectorAll('[data-file-name]'),input:document.querySelector('[data-code-input]'),highlight:document.querySelector('[data-highlight] code'),lineNumbers:document.querySelector('[data-line-numbers]'),cursor:document.querySelector('[data-cursor-position]'),languageStatus:document.querySelector('[data-language-status]'),starters:document.querySelector('[data-starters]'),run:document.querySelector('[data-run]'),reset:document.querySelector('[data-reset]'),preview:document.querySelector('[data-preview]'),output:document.querySelector('[data-output]'),previewState:document.querySelector('[data-preview-state]'),resultTabs:document.querySelectorAll('[data-result-mode]'),saveState:document.querySelector('[data-save-state]'),form:document.querySelector('[data-ai-form]'),prompt:document.querySelector('[data-ai-prompt-input]'),send:document.querySelector('[data-ai-send]'),answer:document.querySelector('[data-ai-answer]'),aiStatus:document.querySelector('[data-ai-status]')};
  let state=loadState(); let authPromise=null; let modelId='chatgpt-5.4-mini'; let lastTerminal='Run a web language to see output here.';
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');const language=languages[saved.language]?saved.language:'html';return {language,codes:saved.codes&&typeof saved.codes==='object'?saved.codes:{}}}catch{return {language:'html',codes:{}}}}
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));refs.saveState.textContent='Saved on this device'}catch{refs.saveState.textContent='Could not save locally'}}
  function code(){return String(state.codes[state.language]??languages[state.language].starter).slice(0,MAX_CODE_CHARS)}
  function setCode(value){state.codes[state.language]=String(value||'').slice(0,MAX_CODE_CHARS);refs.input.value=code();renderEditor();save()}
  function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
  function syntax(value){return escapeHtml(value)+'\n'}
  function renderEditor(){refs.highlight.innerHTML=syntax(refs.input.value);if(refs.lineNumbers)refs.lineNumbers.textContent=Array.from({length:refs.input.value.split('\n').length},(_,index)=>index+1).join('\n');updateCursor();refs.input.scrollTop=refs.highlight.parentElement.scrollTop;refs.input.scrollLeft=refs.highlight.parentElement.scrollLeft}
  function updateCursor(){const before=refs.input.value.slice(0,refs.input.selectionStart);const line=before.split('\n').length;const column=before.length-before.lastIndexOf('\n');const label=`Ln ${line}, Col ${column}`;refs.cursor.textContent=label;document.querySelectorAll('[data-cursor-status]').forEach(item=>item.textContent=label)}
  function renderStarters(){const selected=starters[state.language]||[`${languages[state.language].file} starter`,languages[state.language].starter];refs.starters.innerHTML='';const button=document.createElement('button');button.type='button';button.className='is-active';button.textContent=selected[0];button.addEventListener('click',()=>setCode(selected[1]));refs.starters.append(button)}
  function syncLanguage(){const info=languages[state.language];refs.language.value=state.language;refs.help.textContent=info.help;refs.files.forEach(file=>file.textContent=info.file);if(refs.languageStatus)refs.languageStatus.textContent=state.language==='cpp'?'C++':state.language==='csharp'?'C#':state.language[0].toUpperCase()+state.language.slice(1);refs.input.value=code();renderStarters();renderEditor();setPreviewNote('Not run','');save()}
  function previewDocument(source){if(state.language==='html')return source;if(state.language==='css')return `<!doctype html><style>${source}</style><article class="card"><h1>Styled card</h1><p>Your CSS is running in this safe preview.</p></article>`;return `<!doctype html><style>body{font-family:system-ui;padding:2rem;color:#172033}button{padding:.7rem 1rem;border:0;border-radius:.5rem;background:#4f6ee8;color:white}</style><h1>JavaScript preview</h1><p id="message">Press the button to test your code.</p><button>Try it</button><script>${source.replace(/<\/script/gi,'<\\/script')}<\/script>`}
  function markdown(source){return escapeHtml(source).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n{2,}/g,'</p><p>').replace(/\n/g,'<br>')}
  function setPreviewNote(label,kind){refs.previewState.textContent=label;refs.previewState.className=`preview-state${kind?` is-${kind}`:''}`}
  function setResultMode(mode='output'){refs.resultTabs.forEach(tab=>tab.classList.toggle('is-active',tab.dataset.resultMode===mode));refs.preview.hidden=true;refs.output.hidden=false;if(mode==='terminal'){refs.output.textContent=lastTerminal;return}if(mode==='problems'){const source=code();const messages=[];if(state.language==='json'){try{JSON.parse(source)}catch(error){messages.push(`JSON: ${error.message}`)}}if(!messages.length)messages.push('No problems found in this file.');refs.output.textContent=messages.join('\n');return}if(refs.preview.srcdoc){refs.output.hidden=true;refs.preview.hidden=false}else refs.output.textContent='Run your code to see the result here.'}
  function run(){const source=code();lastTerminal=`> Run ${languages[state.language].file}\n> Updated ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`;if(languages[state.language].run&&['html','css','javascript'].includes(state.language)){const csp='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; script-src \'unsafe-inline\'; img-src data:">';refs.preview.srcdoc=`${csp}${previewDocument(source)}`;setPreviewNote('Live','live');setResultMode('output');return}refs.preview.removeAttribute('srcdoc');if(state.language==='json'){try{refs.output.textContent=JSON.stringify(JSON.parse(source),null,2);setPreviewNote('Valid JSON','live')}catch(error){refs.output.textContent=`JSON error: ${error.message}`;setPreviewNote('Needs a fix','note')}refs.preview.hidden=true;refs.output.hidden=false;return}if(state.language==='markdown'){refs.preview.srcdoc=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><style>html,body{min-height:100%;margin:0;background:#fff}body{font:15px/1.6 system-ui;padding:1.4rem;color:#172033}code{background:#edf1f9;padding:.1rem .25rem;border-radius:.25rem}h1,h2,h3{line-height:1.2}</style><p>${markdown(source)}</p>`;setPreviewNote('Rendered','live');setResultMode('output');return}refs.output.textContent=`${languages[state.language].file} is ready for AI review.\n\nBrowser preview is intentionally limited to HTML, CSS, JavaScript, JSON, and Markdown so Code Sandbox never runs server-side code on your behalf.`;refs.preview.hidden=true;refs.output.hidden=false;setPreviewNote('Editor mode','note')}
  function inheritedTheme(){try{return String(localStorage.getItem('nyx.theme')||'default')}catch{return 'default'}}
  function applyTheme(){document.body.classList.remove('theme-ruby','theme-emerald','theme-sakura','theme-fresh');const theme=inheritedTheme();if(['ruby','emerald','sakura','fresh'].includes(theme))document.body.classList.add(`theme-${theme}`)}
  function focusLanguage(){refs.language.focus()}
  function handleCommand(command){if(command==='reset'){delete state.codes[state.language];syncLanguage();return}if(command==='edit'){refs.input.focus();return}if(command==='select'){refs.input.focus();refs.input.select();return}if(command==='preview'){setResultMode('output');return}if(command==='language'){focusLanguage();return}if(command==='run'){run();return}if(command==='terminal'){setResultMode('terminal')}}
  async function accountToken(){if(parent!==window){const requestId=`code-${Date.now()}-${Math.random().toString(36).slice(2)}`;const parentToken=await new Promise(resolve=>{let done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);removeEventListener('message',receive);resolve(String(value||''))};const receive=event=>{if(event.source===parent&&event.origin===location.origin&&event.data?.type==='nyx:account-token-response'&&event.data.requestId===requestId)finish(event.data.token)};const timer=setTimeout(()=>finish(''),2200);addEventListener('message',receive);parent.postMessage({type:'nyx:account-token-request',requestId},location.origin)});if(parentToken)return parentToken}if(!authPromise)authPromise=(async()=>{try{const response=await fetch('/api/founder-profile/auth-config',{cache:'no-store'});const config=await response.json();if(!config?.enabled||!config?.apiKey||!config?.projectId)return null;const [{initializeApp,getApps},{getAuth,setPersistence,browserLocalPersistence}]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js')]);const app=getApps().find(item=>item.name==='nyx-code-studio')||initializeApp({apiKey:config.apiKey,authDomain:`${config.projectId}.firebaseapp.com`,projectId:config.projectId},'nyx-code-studio');const auth=getAuth(app);try{await setPersistence(auth,browserLocalPersistence)}catch{}if(typeof auth.authStateReady==='function')await auth.authStateReady();return auth}catch{return null}})();try{return authPromise&&authPromise.currentUser?await authPromise.currentUser.getIdToken():''}catch{return ''}}
  async function aiHeaders(){const token=await accountToken();return {'content-type':'application/json','x-nyx-ai-provider':'shared',...(token?{Authorization:`Bearer ${token}`}:{})}}
  async function loadModel(){try{const response=await fetch('/api/nyx-ai/models',{headers:await aiHeaders()});const data=await response.json();if(response.ok&&Array.isArray(data.models)&&data.models[0]?.id)modelId=data.models.find(item=>item.id==='chatgpt-5.4-mini')?.id||data.models[0].id}catch{}}
  function showAnswer(value,error=false){refs.answer.classList.toggle('is-error',error);refs.answer.replaceChildren();const paragraph=document.createElement('p');paragraph.textContent=value;refs.answer.append(paragraph)}
  async function ask(prompt){const question=String(prompt||'').trim();if(!question)return;refs.send.disabled=true;refs.aiStatus.textContent='Thinking';refs.aiStatus.classList.add('is-working');showAnswer('Nyx AI is looking at your code…');try{const response=await fetch('/api/nyx-ai',{method:'POST',headers:await aiHeaders(),body:JSON.stringify({model:modelId,message:`You are helping in Nyx Code Studio. Give a practical, friendly answer for a ${languages[state.language].file} file. Focus on the request, point out the most important issue first, and include a small corrected snippet only when it helps.\n\nUser request: ${question}\n\nCurrent code:\n\n${code()}`,messages:[],responseDepth:'normal',stream:false})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||`Nyx AI could not help (${response.status}).`);showAnswer(String(data?.text||'Nyx AI did not return a suggestion.'));refs.prompt.value=''}catch(error){showAnswer(error?.message||'Nyx AI could not complete that suggestion.',true)}finally{refs.send.disabled=false;refs.aiStatus.textContent='Ready';refs.aiStatus.classList.remove('is-working')}}
  refs.language.addEventListener('change',()=>{state.language=refs.language.value;syncLanguage()});refs.input.addEventListener('input',()=>{state.codes[state.language]=refs.input.value.slice(0,MAX_CODE_CHARS);refs.saveState.textContent='Saving…';renderEditor();save()});refs.input.addEventListener('scroll',()=>{refs.highlight.parentElement.scrollTop=refs.input.scrollTop;refs.highlight.parentElement.scrollLeft=refs.input.scrollLeft;if(refs.lineNumbers)refs.lineNumbers.scrollTop=refs.input.scrollTop});refs.input.addEventListener('keyup',updateCursor);refs.input.addEventListener('click',updateCursor);refs.input.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();const start=refs.input.selectionStart,end=refs.input.selectionEnd;refs.input.setRangeText('  ',start,end,'end');refs.input.dispatchEvent(new Event('input'))}else if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();run()}});refs.run.addEventListener('click',run);document.querySelectorAll('[data-reset]').forEach(button=>button.addEventListener('click',()=>{delete state.codes[state.language];syncLanguage()}));document.querySelector('[data-load-starter]').addEventListener('click',()=>setCode(languages[state.language].starter));refs.resultTabs.forEach(tab=>tab.addEventListener('click',()=>setResultMode(tab.dataset.resultMode)));document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>handleCommand(button.dataset.command)));document.querySelectorAll('[data-activity]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.activity;document.querySelectorAll('[data-activity]').forEach(item=>item.classList.toggle('is-active',item===button));if(action==='explorer'){document.querySelector('.explorer')?.scrollTo({top:0,behavior:'smooth'});return}if(action==='search'){refs.input.focus();refs.input.select();return}if(action==='changes'){lastTerminal='All changes are saved on this device.';setResultMode('terminal');return}if(action==='language'){focusLanguage();return}if(action==='theme'){applyTheme();lastTerminal=`Nyx theme: ${inheritedTheme()}.`;setResultMode('terminal')}}));refs.form.addEventListener('submit',event=>{event.preventDefault();void ask(refs.prompt.value)});document.querySelectorAll('[data-ai-prompt]').forEach(button=>button.addEventListener('click',()=>void ask(button.dataset.aiPrompt)));addEventListener('storage',event=>{if(event.key==='nyx.theme')applyTheme()});applyTheme();syncLanguage();setResultMode('output');void loadModel();
})();
