export function configureModelVoice(payload,modelInfo,{voice='alloy',computerAgent=false,codeEdit=false,generateImage=false}={}){
 if(computerAgent||codeEdit||generateImage||!modelInfo.outputModalities?.includes('audio'))throw Object.assign(new Error('Choose a model with native audio output in Chat mode.'),{status:400});
 if(!/^[a-zA-Z0-9_-]{1,64}$/.test(voice))throw Object.assign(new Error('Invalid voice name.'),{status:400});
 payload.modalities=['text','audio'];payload.audio={voice,format:'mp3'};payload.stream=true;
}
export async function collectModelVoice(response){
 const reader=response.body?.getReader();if(!reader)throw Error('The voice model returned no stream.');
 const decoder=new TextDecoder(),parts=[];let buffer='',transcript='',text='',bytes=0,model='',usage={},finishReason=null;
 function event(raw){if(!raw||raw==='[DONE]')return;const data=JSON.parse(raw);if(data.error)throw Error('The voice provider could not complete this reply.');if(data.model)model=data.model;if(data.usage)usage=data.usage;const choice=data.choices?.[0];if(choice?.finish_reason)finishReason=choice.finish_reason;const delta=choice?.delta||{};if(typeof delta.content==='string')text+=delta.content;if(typeof delta.audio?.transcript==='string')transcript+=delta.audio.transcript;if(delta.audio?.data){if(!/^[A-Za-z0-9+/=]+$/.test(delta.audio.data))throw Error('Invalid voice audio.');const part=Buffer.from(delta.audio.data,'base64');bytes+=part.length;if(bytes>8*1024*1024)throw Error('Voice reply is too large. Ask for a shorter answer.');parts.push(part);}if(text.length+transcript.length>60000)throw Error('Voice transcript is too long.');}
 try{for(;;){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});if(buffer.length>12*1024*1024)throw Error('Voice stream is too large.');let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index).trim();buffer=buffer.slice(index+1);if(line.startsWith('data:'))event(line.slice(5).trim());}}buffer+=decoder.decode();if(buffer.trim().startsWith('data:'))event(buffer.trim().slice(5).trim());if(!bytes)throw Error('This model returned no audio. Try another voice-capable model.');return {model,usage,choices:[{message:{content:transcript||text},finish_reason:finishReason}],voiceAudio:{mime:'audio/mpeg',data:Buffer.concat(parts).toString('base64')}};}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}
}
