(()=>{
  'use strict';
  const API='/api/cloud-gaming';
  const state={games:[],filtered:[],configured:false,token:'',tokenExpiresAt:0,directAuthPromise:null,parentAuth:false,session:null,launching:false,cancelled:false,launchController:null,launchDeadlineTimer:null,launchTimedOut:false,pingTimer:null,elapsedTimer:null,pingFailures:0};
  const LAUNCH_DEADLINE_MS=150_000;
  const refs={
    provider:document.querySelector('[data-provider-state]'),notice:document.querySelector('[data-notice]'),grid:document.querySelector('[data-grid]'),empty:document.querySelector('[data-empty]'),search:document.querySelector('[data-search]'),tag:document.querySelector('[data-tag]'),
    launchLayer:document.querySelector('[data-launch-layer]'),launchTitle:document.querySelector('[data-launch-title]'),launchStatus:document.querySelector('[data-launch-status]'),launchProgress:document.querySelector('[data-launch-progress]'),cancel:document.querySelector('[data-cancel]'),
    playerLayer:document.querySelector('[data-player-layer]'),player:document.querySelector('[data-player]'),playerTitle:document.querySelector('[data-player-title]'),playerTime:document.querySelector('[data-player-time]'),fullscreen:document.querySelector('[data-fullscreen]'),close:document.querySelector('[data-close]')
  };
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function setNotice(message,type=''){refs.notice.textContent=message;refs.notice.className=`notice${type?` ${type}`:''}`}
  function setProvider(label,type=''){refs.provider.querySelector('b').textContent=label;refs.provider.className=`provider-state${type?` ${type}`:''}`}
  function escapeUrl(value){try{const url=new URL(String(value||''),location.href);return url.protocol==='https:'?url.href:''}catch{return''}}
  async function parentToken(){if(window.parent===window)return null;const requestId=`cloud-${Date.now()}-${Math.random().toString(36).slice(2)}`;return new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;clearTimeout(timer);window.removeEventListener('message',receive);resolve(value)};const receive=event=>{if(event.source!==window.parent||event.origin!==location.origin||event.data?.type!=='nyx:account-token-response'||event.data?.requestId!==requestId)return;finish({available:true,token:String(event.data.token||'')})};const timer=setTimeout(()=>finish(null),2500);window.addEventListener('message',receive);window.parent.postMessage({type:'nyx:account-token-request',requestId},location.origin)})}
  async function directAuth(){if(state.directAuthPromise)return state.directAuthPromise;state.directAuthPromise=(async()=>{const config=await requestJson('/api/founder-profile/auth-config',{cache:'no-store'},false);if(!config?.enabled)return null;const [{initializeApp,getApps},{getAuth,setPersistence,browserLocalPersistence}]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js')]);const app=getApps().find(item=>item.name==='nyx-founder-owner')||initializeApp({apiKey:config.apiKey,authDomain:`${config.projectId}.firebaseapp.com`,projectId:config.projectId},'nyx-founder-owner');const auth=getAuth(app);try{await setPersistence(auth,browserLocalPersistence)}catch{}if(typeof auth.authStateReady==='function')await auth.authStateReady();return auth})();try{return await state.directAuthPromise}catch(error){state.directAuthPromise=null;throw error}}
  async function accountToken(force=false){if(!force&&state.token&&state.tokenExpiresAt>Date.now()+30_000)return state.token;const parent=await parentToken();if(parent?.available){state.parentAuth=true;state.token=parent.token;state.tokenExpiresAt=state.token?Date.now()+45*60_000:0;return state.token}state.parentAuth=false;const auth=await directAuth();state.token=auth?.currentUser?await auth.currentUser.getIdToken(force):'';state.tokenExpiresAt=state.token?Date.now()+45*60_000:0;return state.token}
  async function requestJson(path,options={},authorized=true,retry=true){const headers=new Headers(options.headers||{});if(authorized){const token=await accountToken(!retry);if(!token){const error=new Error('Sign in to use Cloud Gaming.');error.status=401;throw error}headers.set('Authorization',`Bearer ${token}`)}const response=await fetch(path,{...options,headers});const contentType=response.headers.get('content-type')||'';let payload=null;if(contentType.includes('application/json'))payload=await response.json();else payload={error:(await response.text()).trim().slice(0,300)};if(!response.ok){if(response.status===401&&authorized&&retry)return requestJson(path,options,true,false);const error=new Error(payload?.error||`Request failed (${response.status}).`);error.status=response.status;throw error}return payload}
  function cardFor(game,index){const article=document.createElement('article');article.className='game-card';const art=document.createElement('div');art.className='game-art';const imageUrl=escapeUrl(game.image||game.cover);if(imageUrl){const image=document.createElement('img');image.src=imageUrl;image.alt='';image.loading=index<18?'eager':'lazy';image.decoding='async';if(index<8)image.fetchPriority='high';image.referrerPolicy='same-origin';image.addEventListener('error',()=>image.remove(),{once:true});art.append(image)}const copy=document.createElement('div');copy.className='game-copy';const title=document.createElement('h3');title.textContent=game.name;title.title=game.name;const tags=document.createElement('div');tags.className='tags';(game.tags||[]).slice(0,3).forEach(tag=>{const item=document.createElement('span');item.textContent=tag;tags.append(item)});const play=document.createElement('button');play.type='button';play.className='play';play.textContent='Play';play.disabled=!state.configured||state.launching;play.addEventListener('click',()=>void launch(game));copy.append(title,tags,play);article.append(art,copy);return article}
  function render(){const query=refs.search.value.trim().toLowerCase();const tag=refs.tag.value.toLowerCase();state.filtered=state.games.filter(game=>(!query||`${game.name} ${game.description} ${(game.tags||[]).join(' ')}`.toLowerCase().includes(query))&&(!tag||(game.tags||[]).some(item=>item.toLowerCase()===tag)));refs.grid.replaceChildren(...state.filtered.map(cardFor));refs.empty.hidden=state.filtered.length>0}
  function populateTags(){const tags=[...new Set(state.games.flatMap(game=>game.tags||[]))].sort((a,b)=>a.localeCompare(b));refs.tag.replaceChildren(new Option('All categories',''),...tags.map(tag=>new Option(tag,tag)))}
  function progress(status,queuePosition){const values={creating_account:18,account_ready:40,requesting_game:58,queue:70,finished_queue:88};refs.launchProgress.style.width=`${values[status]||12}%`;const messages={creating_account:'Preparing a provider session…',account_ready:'Provider session ready.',requesting_game:'Requesting a game server…',queue:`Waiting for a game server${Number.isFinite(queuePosition)?` · position ${queuePosition}`:''}.`,finished_queue:'Game server acquired. Starting stream…'};refs.launchStatus.textContent=messages[status]||'Connecting to the cloud provider…'}
  async function createSession(game,retry=true){const headers=new Headers({'Content-Type':'application/json'});const token=await accountToken(!retry);if(!token)throw new Error('Sign in to use Cloud Gaming.');headers.set('Authorization',`Bearer ${token}`);const response=await fetch(`${API}/sessions`,{method:'POST',headers,body:JSON.stringify({gameKey:game.key}),signal:state.launchController?.signal});if(response.status===401&&retry)return createSession(game,false);if(!response.ok){let payload={};try{payload=await response.json()}catch{}throw new Error(payload.error||`Cloud Gaming returned ${response.status}.`)}if(!response.body)throw new Error('Cloud Gaming did not return session progress.');const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';let finalEvent=null;while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split(/\r?\n/);buffer=done?'':lines.pop()||'';for(const line of lines){if(!line.trim())continue;let event;try{event=JSON.parse(line)}catch{continue}if(event.id)state.session={id:event.id,gameKey:game.key,gameName:game.name,state:event.status==='queue'?'queued':'ready'};progress(event.status,event.queuePosition);finalEvent=event;if(event.status==='error')throw new Error(event.error||'Cloud Gaming could not create this session.')}if(done)break}return finalEvent}
  async function waitForQueue(){while(!state.cancelled&&state.session?.state==='queued'){await sleep(4000);if(state.cancelled)return;const payload=await requestJson(`${API}/sessions/${encodeURIComponent(state.session.id)}/queue`);state.session=payload.session||state.session;progress(payload.status,payload.queuePosition);if(payload.status==='finished_queue'||state.session.state==='ready')return}if(state.cancelled)throw new Error('Launch cancelled.')}
  async function startSession(){const payload=await requestJson(`${API}/sessions/${encodeURIComponent(state.session.id)}/start`,{method:'POST'});state.session=payload.session;if(!state.session?.embedUrl)throw new Error('Cloud Gaming did not return a player address.');openPlayer()}
  async function launch(game){if(state.launching)return;state.launching=true;state.cancelled=false;state.launchTimedOut=false;state.launchController=new AbortController();clearTimeout(state.launchDeadlineTimer);state.launchDeadlineTimer=setTimeout(()=>{state.launchTimedOut=true;state.launchController?.abort()},LAUNCH_DEADLINE_MS);render();refs.launchLayer.hidden=false;refs.launchTitle.textContent=game.name;progress('starting');try{const event=await createSession(game);if(state.cancelled)return;if(event?.status==='queue')await waitForQueue();if(state.cancelled)return;if(!state.session?.id)throw new Error('Cloud Gaming did not create a session.');await startSession()}catch(error){if(!state.cancelled){const message=state.launchTimedOut?'The provider took too long to prepare this game. Try again in a moment.':error?.name==='AbortError'?'Cloud Gaming could not finish preparing this game.':error.message||'Cloud Gaming could not launch this game.';setNotice(message,'error')}await endSession(false)}finally{clearTimeout(state.launchDeadlineTimer);state.launchDeadlineTimer=null;state.launchController=null;state.launching=false;refs.launchLayer.hidden=true;render()}}
  function openPlayer(){refs.playerTitle.textContent=state.session.gameName||'Cloud Gaming';refs.player.src=state.session.embedUrl;refs.playerLayer.hidden=false;refs.launchLayer.hidden=true;state.pingFailures=0;clearInterval(state.pingTimer);state.pingTimer=setInterval(()=>void pingSession(),15000);clearInterval(state.elapsedTimer);state.elapsedTimer=setInterval(updateElapsed,1000);updateElapsed();void pingSession()}
  function updateElapsed(){if(!state.session?.startedAtMs){refs.playerTime.textContent='Connected';return}const used=Math.max(0,Math.floor((Date.now()-state.session.startedAtMs)/1000));const limit=Math.max(0,Number(state.session.maxSeconds||0));refs.playerTime.textContent=limit?`${Math.floor(used/60)}:${String(used%60).padStart(2,'0')} / ${Math.floor(limit/60)}:${String(limit%60).padStart(2,'0')}`:`${Math.floor(used/60)}:${String(used%60).padStart(2,'0')}`}
  async function pingSession(){if(!state.session?.id||state.session.state!=='active')return;try{const usage=await requestJson(`${API}/sessions/${encodeURIComponent(state.session.id)}/ping`,{method:'POST'});state.pingFailures=0;if(usage.sessionTimeLimitSeconds){state.session.maxSeconds=usage.sessionTimeLimitSeconds;state.session.startedAtMs=Date.now()-usage.sessionTimeUsedSeconds*1000;updateElapsed()}}catch(error){state.pingFailures+=1;if(state.pingFailures>=2)setNotice(error.message||'The Cloud Gaming session lost its keepalive.','error')}}
  async function endSession(showNotice=true){const session=state.session;state.cancelled=true;clearTimeout(state.launchDeadlineTimer);state.launchDeadlineTimer=null;state.launchController?.abort();state.session=null;clearInterval(state.pingTimer);clearInterval(state.elapsedTimer);state.pingTimer=null;state.elapsedTimer=null;refs.player.removeAttribute('src');refs.playerLayer.hidden=true;if(session?.id){try{await requestJson(`${API}/sessions/${encodeURIComponent(session.id)}`,{method:'DELETE'})}catch{}}if(showNotice)setNotice('Cloud Gaming session ended.','ready')}
  async function restoreSession(){const payload=await requestJson(`${API}/session`);if(!payload.session)return;state.session=payload.session;if(state.session.state==='active'&&state.session.embedUrl)openPlayer();else if(state.session.state==='queued'){state.launching=true;refs.launchLayer.hidden=false;refs.launchTitle.textContent=state.session.gameName||'Cloud game';try{await waitForQueue();if(!state.cancelled)await startSession()}finally{state.launching=false;refs.launchLayer.hidden=true;render()}}else if(state.session.state==='ready'){state.launching=true;try{await startSession()}finally{state.launching=false;render()}}}
  async function init(){refs.search.addEventListener('input',render);refs.tag.addEventListener('change',render);refs.cancel.addEventListener('click',()=>void endSession(false));refs.close.addEventListener('click',()=>void endSession());refs.fullscreen.addEventListener('click',()=>refs.playerLayer.requestFullscreen?.());document.querySelector('[data-home]').addEventListener('click',event=>{if(window.parent!==window){event.preventDefault();window.parent.postMessage({type:'nyx:go-home'},location.origin)}});try{const status=await requestJson(`${API}/status`,{},false);state.configured=status.configured===true;setProvider(state.configured?'Stratus ready':'Setup required',state.configured?'ready':'error');if(!state.configured)setNotice('Cloud Gaming is installed, but the Owner must add an issued Stratus API key to the OVH environment.','error');const token=await accountToken();if(!token)throw new Error('Sign in to view and launch Cloud Gaming titles.');const catalog=await requestJson(`${API}/catalog`);state.games=Array.isArray(catalog.games)?catalog.games:[];populateTags();render();if(state.configured)setNotice(`${state.games.length} cloud games available. Your provider key stays on the Nyx server.`,'ready');await restoreSession()}catch(error){setNotice(error.message||'Cloud Gaming is unavailable.','error');if(!state.games.length)refs.empty.hidden=false}}
  void init();
})();
