import '/js/owner-dashboard.js';
export function setupDropPresence({frame,ensureAccount,notice}){
 const button=document.getElementById('onlineCounter'),label=document.getElementById('onlineCount');
 const requests=new Map();let signedIn=false,owner=false,revision=0,busy=false,sessionId='';
 try{sessionId=localStorage.getItem('nyx.presenceSession')||'';if(!/^[a-zA-Z0-9_-]{16,128}$/.test(sessionId)){sessionId=crypto.randomUUID();localStorage.setItem('nyx.presenceSession',sessionId);}}catch{sessionId=crypto.randomUUID();}
 function access(value){owner=value;const role=document.getElementById('accountRole');role.textContent=owner?'Owner ? Full access':signedIn?'Member ? Standard access':'Guest';role.dataset.role=owner?'owner':signedIn?'member':'guest';button.disabled=!owner;button.title=owner?'Open Owner Dashboard':'Current users online';button.setAttribute('aria-label',owner?'Open Owner Dashboard':'Current users online');}
 function getToken(){ensureAccount();const requestId=crypto.randomUUID();return new Promise(resolve=>{const timer=setTimeout(()=>{requests.delete(requestId);resolve('');},4000);requests.set(requestId,token=>{clearTimeout(timer);resolve(token);});frame.contentWindow?.postMessage({type:'drop:session-token',requestId},location.origin);});}
 async function refreshAccess(){const mine=++revision;access(false);try{const token=await getToken();if(!token)return;const r=await fetch('/api/founder-profile/owner',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(8000)});const data=r.ok?await r.json():{};if(mine===revision)access(data.founder===true&&data.dashboard===true);}catch{if(mine===revision)access(false);}}
 async function heartbeat(){if(busy||document.hidden)return;busy=true;try{const token=await getToken();const r=await fetch('/api/presence',{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({sessionId}),cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error();const data=await r.json();if(!Number.isFinite(data.online)||data.online<0)throw Error();label.textContent=Math.floor(data.online)+' online';button.classList.remove('unavailable');}catch{label.textContent='Online unavailable';button.classList.add('unavailable');}finally{busy=false;}}
 addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==frame.contentWindow)return;const data=event.data;if(data?.type==='drop:session-token-result'){const complete=requests.get(data.requestId);requests.delete(data.requestId);complete?.(typeof data.token==='string'?data.token:'');}if(data?.type==='drop:account'){signedIn=data.signedIn===true;revision++;access(false);globalThis.NyxOwnerDashboard?.close();if(data.signedIn)void refreshAccess();void heartbeat();}if(data?.type==='drop:ready'){void refreshAccess();void heartbeat();}});
 button.onclick=async()=>{if(!owner)return;await refreshAccess();if(!owner){notice('Owner access is unavailable.');return;}globalThis.NyxOwnerDashboard.open({getToken,toast:notice});};
 document.addEventListener('visibilitychange',()=>{if(!document.hidden){void heartbeat();void refreshAccess();}});addEventListener('online',heartbeat);
 access(false);ensureAccount();void heartbeat();setInterval(heartbeat,15000);
}
