import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
await page.addInitScript(()=>{window.WebSocket=class{constructor(){throw Error('Native WebSocket disabled for bridge test');}};});
await page.route('**/assets/transports/epoxy-scramjet.mjs',r=>r.fulfill({contentType:'text/javascript',body:`export default class {ready=false;async init(){this.ready=true}async request(remote){await new Promise(resolve=>setTimeout(resolve,500));return {status:200,statusText:'OK',headers:[['content-type','text/html']],body:new Response('<!doctype html><title>Fixture</title><h1>Drop page</h1><button id="spa" onclick="history.pushState({},String(),String.fromCharCode(47,110,101,120,116));document.title=String.fromCharCode(83,80,65)">Change route</button><a href="https://fixture.test/next">Next</a>'+' '.repeat(500000)).body}}connect(){return [()=>{},()=>{}]}}`}));
await page.goto(process.env.DROP_TEST_URL||'http://localhost:6767/apps/drop/');assert.equal(await page.title(),'Drop');assert.equal(await page.getByText('A little less noise.').count(),0);
await page.locator('#collapse').click();assert.equal(await page.locator('#collapse').getAttribute('aria-expanded'),'false');assert(await page.locator('#shortcuts button').evaluateAll(nodes=>nodes.every(el=>el.scrollWidth<=el.clientWidth+1&&el.getBoundingClientRect().width>70)));await page.locator('#collapse').click();
await page.locator('#query').fill('https://fixture.test/one');await page.locator('#search button').click();await page.locator('#reload').click();await page.waitForFunction(()=>getComputedStyle(document.querySelector('.browser-bar'),'::after').animationName==='drop-loading-sweep');await page.frameLocator('#stage iframe:not([hidden])').getByRole('heading',{name:'Drop page'}).waitFor({timeout:45000});
await page.waitForFunction(()=>parseFloat(document.getElementById('speed').textContent)>0,{timeout:6000});assert.equal(await page.locator('.browser-bar').evaluate(el=>getComputedStyle(el,'::after').animationName),'none');await page.frameLocator('#stage iframe:not([hidden])').locator('#spa').click();await page.waitForFunction(()=>new URL(document.getElementById('address').value).pathname==='/next');assert.match(await page.locator('#tabs').innerText(),/SPA/);await page.locator('#homeNav').click();assert.equal(await page.locator('#query').inputValue(),'');
await page.locator('#query').fill('https://fixture.test/two');await page.locator('#search button').click();await page.frameLocator('#stage iframe:not([hidden])').getByRole('heading',{name:'Drop page'}).waitFor();assert.equal(await page.locator('#tabs .tab').count(),2);
await page.locator('#tabs .tab button').first().click();assert.match(await page.locator('#address').inputValue(),/next/);await page.locator('#reload').click();await page.frameLocator('#stage iframe:not([hidden])').getByRole('heading',{name:'Drop page'}).waitFor();
await page.locator('#bookmarkPage').click();await page.locator('#pinPage').click();assert.equal(await page.locator('#tabs .tab').first().getAttribute('class'),'tab pinned');
await page.locator('#bookmarksNav').click();assert.equal(await page.locator('#bookmarkList .bookmark-row').count(),1);await page.locator('#bookmarkSearch').fill('no-match');assert.equal(await page.locator('#bookmarkList .bookmark-row').count(),0);await page.locator('#bookmarkSearch').fill('');await page.locator('#bookmarkList .bookmark-row button').first().click();assert.equal(await page.locator('#tabs .tab').count(),3);
await page.locator('#settingsButton').click();await page.locator('#engine').selectOption('bing');await page.locator('#connectionMode').selectOption('bridge');await page.locator('#popups').uncheck();await page.locator('[data-close=settings]').click();await page.reload();assert.equal(await page.locator('#tabs .tab').count(),3);assert.equal(await page.locator('#tabs .tab.pinned').count(),1);await page.locator('#bookmarksNav').click();assert.equal(await page.locator('#bookmarkList .bookmark-row').count(),1);await page.locator('#bookmarkList .icon').click();assert.equal(await page.locator('#bookmarkList .bookmark-row').count(),0);assert.equal(await page.locator('#engine').inputValue(),'bing');assert.equal(await page.locator('#connectionMode').inputValue(),'bridge');assert.equal(await page.locator('#popups').isChecked(),false);
await page.locator('#aiNav').click();const ai=page.frameLocator('#aiFrame');await ai.locator('#dropHistory').click();await ai.locator('#chatSearch').waitFor();await ai.locator('#collapseChats').click();await ai.locator('#chatSearch').waitFor({state:'hidden'});
await page.locator('#settingsButton').click();await page.locator('#keys').click();await ai.locator('#keyDialog').waitFor();await ai.locator('#closeKeys').click();await page.locator('#profile').click();await page.locator('#accountAction').click();await ai.locator('#login').waitFor();await ai.locator('#closeLogin').click();
await page.locator('#homeNav').click();await page.setViewportSize({width:390,height:844});if(await page.locator('#collapse').getAttribute('aria-expanded')==='true')await page.locator('#collapse').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS Drop tabs, proxy navigation/reload, real byte graph, settings persistence, AI history/keys/login and mobile rail');
}finally{await browser.close();}
