import {secondaryLessons,secondaryProblem} from './secondary.mjs';
export const units=[
 {id:'grade7',name:'Grade 7 Math',level:'Ratios and number skills',description:'Fractions, percentages, ratios, and signed numbers.'},
 {id:'grade8',name:'Grade 8 Math',level:'Pre-algebra',description:'Equations, coordinate distance, and triangle angles.'},
 {id:'grade9',name:'Grade 9 Math',level:'Algebra I',description:'Distributive equations, slope, linear functions, and systems.'},
 {id:'grade10',name:'Grade 10 Math',level:'Geometry and quadratics',description:'Area, right triangles, coordinate geometry, and quadratic roots.'},
 {id:'grade11',name:'Grade 11 Math',level:'Algebra II and trigonometry',description:'Exponents, logarithms, trigonometric ratios, and arithmetic sequences.'},
 {id:'grade12',name:'Grade 12 Math',level:'Precalculus and calculus introduction',description:'Polynomials, function composition, geometric sequences, and derivatives.'}
];
export const lessons=[
 {id:'fractions',unit:'foundations',name:'Add fractions',objective:'Add fractions using a common denominator.',rule:'Multiply the numerator and denominator by the same number to make equivalent fractions. Add the numerators; keep the common denominator.',steps:['Find a common multiple of the denominators.','Rewrite both fractions with that denominator.','Add the numerators, then simplify if possible.'],examples:[{question:'1/3 + 1/4',work:['A common denominator is 12.','1/3 = 4/12 and 1/4 = 3/12.','4/12 + 3/12 = 7/12.']},{question:'2/5 + 1/10',work:['Use a denominator of 10.','2/5 = 4/10.','4/10 + 1/10 = 5/10 = 1/2.']}],mistake:'Do not add the denominators. They describe the size of each part, and that size must stay the same.'},
 {id:'percentages',unit:'foundations',name:'Percent of a number',objective:'Convert a percent to a decimal and find a part of a whole.',rule:'A percent is a number out of 100. To find p% of a number, multiply that number by p ÷ 100.',steps:['Divide the percent by 100.','Multiply the resulting decimal by the whole.','Check that a percent below 100 gives a result smaller than the whole.'],examples:[{question:'Find 15% of 80.',work:['15 ÷ 100 = 0.15.','0.15 × 80 = 12.']},{question:'Find 25% of 60.',work:['25 ÷ 100 = 0.25.','0.25 × 60 = 15.','You can also divide 60 by 4 because 25% is one quarter.']}],mistake:'15% means 0.15, not 15. Forgetting to divide by 100 makes the answer one hundred times too large.'},
 {id:'ratios',unit:'foundations',name:'Equivalent ratios',objective:'Scale both parts of a ratio by the same factor.',rule:'Equivalent ratios compare amounts in the same proportion. Multiply or divide both quantities by the same nonzero number.',steps:['Find the multiplier between the known quantities.','Apply that multiplier to the other quantity.','Check both pairs describe the same comparison.'],examples:[{question:'3 notebooks cost $6. What do 7 notebooks cost?',work:['One notebook costs 6 ÷ 3 = $2.','Seven notebooks cost 7 × 2 = $14.']},{question:'A recipe uses 2 cups of rice for 3 cups of water. How much water for 6 cups of rice?',work:['6 ÷ 2 = 3, so the recipe is tripled.','3 × 3 = 9 cups of water.']}],mistake:'Adding the same amount to both sides of a ratio usually changes the ratio. Use multiplication or division.'},
 {id:'one-step',unit:'algebra',name:'One-step equations',objective:'Use an inverse operation to isolate the variable.',rule:'An equation is a balance. Adding or subtracting the same amount on both sides keeps it balanced.',steps:['Identify what has been added to or subtracted from x.','Undo that operation on both sides.','Substitute your answer into the original equation.'],examples:[{question:'x + 7 = 19',work:['Subtract 7 from both sides.','x = 19 − 7 = 12.','Check: 12 + 7 = 19.']},{question:'x − 5 = 8',work:['Add 5 to both sides.','x = 8 + 5 = 13.']}],mistake:'Whatever you do to one side of the equation, do to the other side too.'},
 {id:'two-step',unit:'algebra',name:'Two-step equations',objective:'Solve equations in the form ax + b = c.',rule:'Undo addition or subtraction first, then undo multiplication or division. This isolates x while keeping both sides equal.',steps:['Subtract the constant from both sides.','Divide both sides by the coefficient of x.','Substitute the result to check it.'],examples:[{question:'3x + 5 = 20',work:['Subtract 5: 3x = 15.','Divide by 3: x = 5.','Check: 3 × 5 + 5 = 20.']},{question:'4x + 2 = 30',work:['Subtract 2: 4x = 28.','Divide by 4: x = 7.']}],mistake:'Divide the entire remaining side by the coefficient, not just one term of the original equation.'},
 {id:'distribute',unit:'algebra',name:'Equations with parentheses',objective:'Solve equations using the distributive property.',rule:'The multiplier outside parentheses applies to every term inside: a(x + b) = ax + ab.',steps:['Distribute the outside factor to both terms.','Undo the constant term.','Divide by the coefficient of x.'],examples:[{question:'2(x + 3) = 18',work:['Distribute: 2x + 6 = 18.','Subtract 6: 2x = 12.','Divide by 2: x = 6.']},{question:'3(x + 4) = 27',work:['Distribute: 3x + 12 = 27.','Subtract 12: 3x = 15.','Divide by 3: x = 5.']}],mistake:'2(x + 3) is 2x + 6, not 2x + 3. Both terms inside the parentheses must be multiplied.'},
 {id:'area',unit:'geometry',name:'Area of a triangle',objective:'Find triangle area from perpendicular base and height.',rule:'A triangle has half the area of a rectangle with the same base and perpendicular height: A = ½ × b × h.',steps:['Identify the base and its perpendicular height.','Multiply base by height.','Divide by 2 and use square units.'],examples:[{question:'Base = 8 cm, height = 5 cm. Find the area.',work:['8 × 5 = 40.','40 ÷ 2 = 20 cm².']},{question:'Base = 12 m, height = 7 m. Find the area.',work:['12 × 7 = 84.','84 ÷ 2 = 42 m².']}],mistake:'The slanted side is not necessarily the height. Height must meet the base at a right angle.'},
 {id:'angles',unit:'geometry',name:'Missing triangle angles',objective:'Use the angle sum of a triangle to find an unknown angle.',rule:'The three interior angles of a triangle add to 180°. Subtract the two known angles from 180°.',steps:['Add the two known angles.','Subtract their sum from 180°.','Check all three angles now add to 180°.'],examples:[{question:'Two angles are 45° and 65°. Find the third.',work:['45 + 65 = 110.','180 − 110 = 70°.']},{question:'A right triangle has another angle of 35°. Find the remaining angle.',work:['A right angle is 90°.','180 − 90 − 35 = 55°.']}],mistake:'Use 180° for the interior angle sum of a triangle, not 360°.'},
 {id:'pythagorean',unit:'geometry',name:'The Pythagorean theorem',objective:'Find the hypotenuse of a right triangle.',rule:'For a right triangle, a² + b² = c². The hypotenuse c is opposite the right angle and is the longest side.',steps:['Square each of the two leg lengths.','Add those squares.','Take the square root to find the hypotenuse.'],examples:[{question:'The legs are 3 and 4. Find the hypotenuse.',work:['3² + 4² = 9 + 16 = 25.','c² = 25, so c = 5.']},{question:'The legs are 5 and 12. Find the hypotenuse.',work:['5² + 12² = 25 + 144 = 169.','c = √169 = 13.']}],mistake:'Adding the leg lengths does not find the hypotenuse. Square first, add, then take the square root.'}
];
const gradeForSkill={fractions:'grade7',percentages:'grade7',ratios:'grade7','one-step':'grade8','two-step':'grade8',angles:'grade8',distribute:'grade9',area:'grade10',pythagorean:'grade10'};
for(const lesson of lessons)lesson.unit=gradeForSkill[lesson.id];
lessons.push(...secondaryLessons);
export function numericAnswer(raw){
 const text=String(raw).trim();
 if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:\s*\/\s*[+-]?(?:\d+(?:\.\d*)?|\.\d+))?$/.test(text))return null;
 const values=text.split('/').map(Number),value=values.length===2?values[0]/values[1]:values[0];return Number.isFinite(value)?value:null;
}
export function correctAnswer(raw,answer){const value=numericAnswer(raw);return value!==null&&Math.abs(value-answer)<1e-8;}
export function makeProblem(id,random=Math.random){
 if(secondaryLessons.some(lesson=>lesson.id===id))return secondaryProblem(id,random);
 const int=(a,b)=>a+Math.floor(random()*(b-a+1));
 const a=int(2,9),b=int(2,9),x=int(1,12);
 switch(id){
  case 'fractions':{const n=int(1,a-1),m=int(1,b-1),top=n*b+m*a,bot=a*b;return {prompt:`${n}/${a} + ${m}/${b}`,answer:top/bot,hint:`Use ${bot} as a common denominator.`,steps:[`${n}/${a} = ${n*b}/${bot}; ${m}/${b} = ${m*a}/${bot}.`,`Add the numerators: ${top}/${bot}. Equivalent fractions are accepted.`]};}
  case 'percentages':{const percent=int(1,9)*5,whole=int(2,20)*20;return {prompt:`Find ${percent}% of ${whole}.`,answer:percent*whole/100,hint:'Divide the percent by 100 before multiplying.',steps:[`${percent} ÷ 100 = ${percent/100}.`,`${percent/100} × ${whole} = ${percent*whole/100}.`]};}
  case 'ratios':return {prompt:`${a} notebooks cost $${a*b}. How much do ${x} notebooks cost?`,answer:b*x,hint:'First find the cost of one notebook.',steps:[`One notebook costs ${a*b} ÷ ${a} = $${b}.`,`${x} notebooks cost ${x} × ${b} = $${x*b}.`]};
  case 'one-step':return {prompt:`x + ${a} = ${x+a}`,answer:x,hint:`Subtract ${a} from both sides.`,steps:[`x = ${x+a} − ${a}.`,`x = ${x}.`]};
  case 'two-step':return {prompt:`${a}x + ${b} = ${a*x+b}`,answer:x,hint:`Subtract ${b}, then divide by ${a}.`,steps:[`${a}x = ${a*x+b} − ${b} = ${a*x}.`,`x = ${a*x} ÷ ${a} = ${x}.`]};
  case 'distribute':return {prompt:`${a}(x + ${b}) = ${a*(x+b)}`,answer:x,hint:`Multiply both x and ${b} by ${a}.`,steps:[`${a}x + ${a*b} = ${a*(x+b)}.`,`${a}x = ${a*x}.`,`x = ${x}.`]};
  case 'area':return {prompt:`A triangle has base ${a*2} cm and perpendicular height ${b} cm. Find its area in cm².`,answer:a*b,hint:'Area = base × height ÷ 2.',steps:[`${a*2} × ${b} = ${a*2*b}.`,`${a*2*b} ÷ 2 = ${a*b} cm².`],diagram:'triangle',labels:[`${a*2} cm`,`${b} cm`]};
  case 'angles':{const p=a*5,q=b*5;return {prompt:`A triangle has angles ${p}° and ${q}°. Find the third angle in degrees.`,answer:180-p-q,hint:'All three angles sum to 180°.',steps:[`${p} + ${q} = ${p+q}.`,`180 − ${p+q} = ${180-p-q}°.`]};}
  case 'pythagorean':{const triples=[[3,4,5],[5,12,13],[8,15,17],[7,24,25]],t=triples[int(0,3)],scale=int(1,8),p=t[0]*scale,q=t[1]*scale,c=t[2]*scale;return {prompt:`A right triangle has legs ${p} and ${q}. Find the hypotenuse.`,answer:c,hint:'Use a² + b² = c².',steps:[`${p}² + ${q}² = ${p*p} + ${q*q} = ${c*c}.`,`The positive square root of ${c*c} is ${c}.`],diagram:'triangle',labels:[String(p),String(q)]};}
  default:throw new Error('Unknown skill');
 }
}
