// Suggested grade groupings, not a claim of alignment to a particular school curriculum.
export const secondaryLessons=[
 {id:'integers',unit:'grade7',name:'Add signed integers',objective:'Add positive and negative integers.',rule:'Adding a positive number moves right on the number line. Adding a negative number moves left.',steps:['Start at the first integer.','Move in the direction of the second integer.','Read the final position.'],examples:[{question:'−4 + 9',work:['Start at −4 and move 9 units right.','The result is 5.']},{question:'3 + (−8)',work:['Start at 3 and move 8 units left.','The result is −5.']}],mistake:'The rule “two negatives make a positive” is for multiplication or division, not for adding two negative numbers.'},
 {id:'coordinates',unit:'grade8',name:'Distance on a coordinate grid',objective:'Find horizontal distance between points.',rule:'When two points have the same y-coordinate, their distance is the absolute difference of their x-coordinates.',steps:['Confirm the y-coordinates match.','Subtract the smaller x-coordinate from the larger.','Report the distance as a nonnegative number.'],examples:[{question:'Distance between (−2, 3) and (5, 3)',work:['Both points have y = 3.','5 − (−2) = 7 units.']},{question:'Distance between (−6, 1) and (−1, 1)',work:['Both points have y = 1.','−1 − (−6) = 5 units.']}],mistake:'Distance measures separation, so it cannot be negative.'},
 {id:'slope',unit:'grade9',name:'Slope from two points',objective:'Calculate a line’s rate of change.',rule:'Slope is rise divided by run: m = (y₂ − y₁)/(x₂ − x₁). Keep the same point order in both differences.',steps:['Find the change in y.','Find the change in x using the same order.','Divide rise by run.'],examples:[{question:'Slope through (1, 2) and (4, 8)',work:['Rise = 8 − 2 = 6. Run = 4 − 1 = 3.','m = 6/3 = 2.']},{question:'Slope through (0, 5) and (2, 1)',work:['Rise = 1 − 5 = −4. Run = 2 − 0 = 2.','m = −4/2 = −2.']}],mistake:'A vertical line has zero run and undefined slope. It does not have slope zero.'},
 {id:'linear-functions',unit:'grade9',name:'Evaluate linear functions',objective:'Find outputs of a linear function.',rule:'For f(x) = mx + b, replace x with the given input. Multiply first, then add the constant.',steps:['Substitute the input for x.','Perform multiplication.','Add or subtract the constant.'],examples:[{question:'f(x) = 3x + 2. Find f(4).',work:['f(4) = 3(4) + 2.','f(4) = 14.']},{question:'g(x) = −2x + 5. Find g(−3).',work:['g(−3) = −2(−3) + 5.','g(−3) = 11.']}],mistake:'f(4) means the function’s output at input 4. It does not mean f multiplied by 4.'},
 {id:'systems',unit:'grade9',name:'Systems by substitution',objective:'Find the intersection of two lines.',rule:'At an intersection, both equations have the same x and y values. If both equations give y, set their expressions equal.',steps:['Set the expressions for y equal.','Solve the resulting equation for x.','Substitute x into either equation to find y and check both.'],examples:[{question:'y = 2x + 1 and y = x + 4',work:['2x + 1 = x + 4, so x = 3.','y = 2(3) + 1 = 7.','The solution is (3, 7).']},{question:'y = 3x − 2 and y = x + 6',work:['3x − 2 = x + 6, so 2x = 8 and x = 4.','y = 10. The solution is (4, 10).']}],mistake:'An x-value alone is not the full solution pair. These practice questions ask specifically for x; use y to check your work.'},
 {id:'quadratics',unit:'grade10',name:'Quadratic equations by factoring',objective:'Find roots using the zero-product property.',rule:'If (x − a)(x − b) = 0, at least one factor is zero. The roots are x = a and x = b.',steps:['Factor the quadratic into two binomials.','Set each factor equal to zero.','Solve both equations and check which root the question requests.'],examples:[{question:'x² − 7x + 12 = 0',work:['Factor: (x − 3)(x − 4) = 0.','The roots are 3 and 4. The smaller root is 3.']},{question:'x² − 2x − 15 = 0',work:['Factor: (x − 5)(x + 3) = 0.','The roots are 5 and −3. The smaller root is −3.']}],mistake:'A quadratic may have two roots. Give the requested root rather than dropping one without checking.'},
 {id:'distance',unit:'grade10',name:'The distance formula',objective:'Find distance between any two points.',rule:'Distance = √((x₂ − x₁)² + (y₂ − y₁)²). The differences are the legs of a right triangle.',steps:['Find the horizontal and vertical changes.','Square each change and add.','Take the nonnegative square root.'],examples:[{question:'Distance from (1, 2) to (4, 6)',work:['Changes: 4 − 1 = 3 and 6 − 2 = 4.','Distance = √(9 + 16) = 5.']},{question:'Distance from (−2, 1) to (3, 13)',work:['Changes: 5 horizontally and 12 vertically.','Distance = √(25 + 144) = 13.']}],mistake:'Square each difference before adding. Do not square the sum of the differences.'},
 {id:'exponents',unit:'grade11',name:'Exponent rules',objective:'Combine powers with the same base.',rule:'For the same nonzero base, multiply powers by adding exponents: a^m × a^n = a^(m+n). Divide powers by subtracting exponents.',steps:['Check that the bases match.','Add exponents for multiplication or subtract for division.','Keep the original base.'],examples:[{question:'2³ × 2⁴ = 2^k. Find k.',work:['The bases match.','k = 3 + 4 = 7.']},{question:'5⁶ ÷ 5² = 5^k. Find k.',work:['Subtract the exponents.','k = 6 − 2 = 4.']}],mistake:'Do not add the bases or multiply the exponents when multiplying powers with the same base.'},
 {id:'logarithms',unit:'grade11',name:'Evaluate logarithms',objective:'Rewrite logarithms as exponential equations.',rule:'log_b(a) = c means b^c = a, where b > 0, b ≠ 1, and a > 0.',steps:['Identify the base and argument.','Ask what power of the base equals the argument.','Check by exponentiation.'],examples:[{question:'log₂(32)',work:['2⁵ = 32.','Therefore log₂(32) = 5.']},{question:'log₃(1/9)',work:['3^(−2) = 1/9.','Therefore log₃(1/9) = −2.']}],mistake:'The argument is not multiplied by the base. A logarithm asks for an exponent.'},
 {id:'trigonometry',unit:'grade11',name:'Right-triangle trigonometry',objective:'Find sine and cosine ratios in a right triangle.',rule:'For an acute angle θ, sin θ = opposite/hypotenuse and cos θ = adjacent/hypotenuse.',steps:['Locate the reference angle.','Identify the opposite, adjacent, and hypotenuse sides.','Select the two sides used by the requested ratio.'],examples:[{question:'Opposite = 3, adjacent = 4, hypotenuse = 5. Find sin θ.',work:['Sine uses opposite over hypotenuse.','sin θ = 3/5.']},{question:'Opposite = 5, adjacent = 12, hypotenuse = 13. Find cos θ.',work:['Cosine uses adjacent over hypotenuse.','cos θ = 12/13.']}],mistake:'Opposite and adjacent depend on the reference angle. The hypotenuse is always opposite the right angle.'},
 {id:'arithmetic-sequences',unit:'grade11',name:'Arithmetic sequences',objective:'Find a term of a sequence with constant difference.',rule:'The nth term is a_n = a₁ + (n − 1)d, where a₁ is the first term and d is the common difference.',steps:['Identify the first term and common difference.','Count n − 1 changes from the first term.','Multiply the difference by n − 1 and add to the first term.'],examples:[{question:'4, 7, 10, … Find the 8th term.',work:['a₁ = 4 and d = 3.','a₈ = 4 + 7(3) = 25.']},{question:'20, 16, 12, … Find the 6th term.',work:['a₁ = 20 and d = −4.','a₆ = 20 + 5(−4) = 0.']}],mistake:'The first term is already counted. Use n − 1 differences, not n differences.'},
 {id:'polynomial-remainder',unit:'grade12',name:'The remainder theorem',objective:'Find the remainder when dividing by x − a.',rule:'When a polynomial f(x) is divided by x − a, the remainder is f(a).',steps:['Identify a from the divisor x − a.','Substitute a into the polynomial.','Evaluate; the result is the remainder.'],examples:[{question:'Remainder of (x² + 3x + 2) ÷ (x − 2)',work:['Evaluate f(2).','2² + 3(2) + 2 = 12.']},{question:'Remainder of (x² − x + 4) ÷ (x + 1)',work:['x + 1 = x − (−1), so evaluate f(−1).','(−1)² − (−1) + 4 = 6.']}],mistake:'For a divisor x + 1, substitute −1, not 1.'},
 {id:'composition',unit:'grade12',name:'Composition of functions',objective:'Evaluate one function inside another.',rule:'(f ∘ g)(x) = f(g(x)). Evaluate the inside function first, then use its output as the input to the outside function.',steps:['Find g(x) for the given input.','Substitute that result into f.','Evaluate f to finish.'],examples:[{question:'f(x) = 2x + 1, g(x) = x². Find f(g(3)).',work:['g(3) = 9.','f(9) = 2(9) + 1 = 19.']},{question:'f(x) = x², g(x) = x + 4. Find f(g(2)).',work:['g(2) = 6.','f(6) = 36.']}],mistake:'f(g(x)) and g(f(x)) can have different values. Follow the requested order.'},
 {id:'geometric-sequences',unit:'grade12',name:'Geometric sequences',objective:'Find terms in a sequence with constant ratio.',rule:'The nth term is a_n = a₁ × r^(n−1), where r is the common ratio.',steps:['Identify the first term and ratio.','Raise the ratio to n − 1.','Multiply by the first term.'],examples:[{question:'3, 6, 12, … Find the 6th term.',work:['a₁ = 3 and r = 2.','a₆ = 3 × 2⁵ = 96.']},{question:'80, 40, 20, … Find the 5th term.',work:['a₁ = 80 and r = 1/2.','a₅ = 80 × (1/2)⁴ = 5.']}],mistake:'A constant ratio uses multiplication, unlike the constant difference of an arithmetic sequence.'},
 {id:'derivatives',unit:'grade12',name:'Introduction to derivatives',objective:'Use the power rule to find a slope at a point.',rule:'For f(x) = ax^n, the derivative is f′(x) = an x^(n−1). A derivative gives the instantaneous rate of change. This is an introductory calculus topic.',steps:['Multiply the coefficient by the exponent.','Reduce the exponent by 1.','Evaluate the derivative at the requested x-value.'],examples:[{question:'f(x) = 3x². Find f′(2).',work:['f′(x) = 6x.','f′(2) = 12.']},{question:'f(x) = 2x³. Find f′(−1).',work:['f′(x) = 6x².','f′(−1) = 6.']}],mistake:'Evaluate the derivative, not the original function, when asked for the instantaneous rate of change.'}
];
export function secondaryProblem(id,random){
 const int=(a,b)=>a+Math.floor(random()*(b-a+1));
 const a=int(2,8),b=int(1,9),x=int(-5,8);
 switch(id){
  case 'integers':{const y=int(-12,12);return {prompt:`${x} + (${y})`,answer:x+y,hint:'Use the direction of the second addend on a number line.',steps:[`Start at ${x} and move ${Math.abs(y)} units ${y<0?'left':'right'}.`,`The result is ${x+y}.`]};}
  case 'coordinates':{const d=int(2,15);return {prompt:`Find the distance between (${x}, ${b}) and (${x+d}, ${b}).`,answer:d,hint:'Find the absolute difference of the x-coordinates.',steps:[`${x+d} − (${x}) = ${d}.`,`Distance = ${d} units.`]};}
  case 'slope':{const rise=int(-12,12),run=int(1,6);return {prompt:`Find the slope through (${x}, ${b}) and (${x+run}, ${b+rise}).`,answer:rise/run,hint:'Divide the change in y by the change in x.',steps:[`Rise = ${rise}; run = ${run}.`,`Slope = ${rise}/${run}.`]};}
  case 'linear-functions':return {prompt:`f(x) = ${a}x + ${b}. Find f(${x}).`,answer:a*x+b,hint:'Substitute the input, multiply, then add.',steps:[`f(${x}) = ${a}(${x}) + ${b}.`,`f(${x}) = ${a*x+b}.`]};
  case 'systems':{const c=b+(a-1)*x;return {prompt:`y = ${a}x + ${b} and y = x + (${c}). Find x at the intersection.`,answer:x,hint:'Set the right-hand sides equal.',steps:[`${a}x + ${b} = x + (${c}).`,`${a-1}x = ${c-b}.`,`x = ${x}; y = ${a*x+b}.`]};}
  case 'quadratics':{const r=int(-7,1),s=int(2,9),sum=r+s,product=r*s;return {prompt:`x² − (${sum})x + (${product}) = 0. Find the smaller root.`,answer:r,hint:'Find two roots whose sum and product match the coefficients.',steps:[`Factor as (x − (${r}))(x − ${s}) = 0.`,`The roots are ${r} and ${s}. The smaller root is ${r}.`]};}
  case 'distance':{const scale=int(1,5),dx=3*scale,dy=4*scale;return {prompt:`Find the distance between (${x}, ${b}) and (${x+dx}, ${b+dy}).`,answer:5*scale,hint:'Use the Pythagorean theorem on the coordinate differences.',steps:[`Changes: ${dx} and ${dy}.`,`Distance = √(${dx*dx} + ${dy*dy}) = ${5*scale}.`]};}
  case 'exponents':{const m=int(1,9),n=int(1,9),divide=random()<.5;return {prompt:`${a}^${m} ${divide?'÷':'×'} ${a}^${n} = ${a}^k. Find k.`,answer:divide?m-n:m+n,hint:divide?'Subtract the exponents.':'Add the exponents.',steps:[`k = ${m} ${divide?'−':'+'} ${n} = ${divide?m-n:m+n}.`]};}
  case 'logarithms':{const base=int(2,5),power=int(-3,5),arg=power<0?`1/${base**(-power)}`:String(base**power);return {prompt:`Find log base ${base} of (${arg}).`,answer:power,hint:'What exponent on the base gives the argument?',steps:[`${base}^(${power}) = ${arg}.`,`The logarithm is ${power}.`]};}
  case 'trigonometry':{const triples=[[3,4,5],[5,12,13],[8,15,17]],t=triples[int(0,2)],scale=int(1,4),cos=random()<.5,numerator=cos?t[1]:t[0];return {prompt:`Relative to θ, opposite = ${t[0]*scale}, adjacent = ${t[1]*scale}, hypotenuse = ${t[2]*scale}. Find ${cos?'cos':'sin'} θ.`,answer:numerator/t[2],hint:cos?'Cosine = adjacent/hypotenuse.':'Sine = opposite/hypotenuse.',steps:[`${cos?'cos':'sin'} θ = ${numerator*scale}/${t[2]*scale} = ${numerator}/${t[2]}.`]};}
  case 'arithmetic-sequences':{const d=int(-6,6),n=int(4,12);return {prompt:`An arithmetic sequence has first term ${x} and common difference ${d}. Find term ${n}.`,answer:x+(n-1)*d,hint:'Use a_n = a₁ + (n − 1)d.',steps:[`a_${n} = ${x} + (${n} − 1)(${d}).`,`a_${n} = ${x+(n-1)*d}.`]};}
  case 'polynomial-remainder':return {prompt:`f(x) = x² + ${a}x + ${b}. Find the remainder when divided by x − (${x}).`,answer:x*x+a*x+b,hint:`Use the remainder theorem: evaluate f(${x}).`,steps:[`f(${x}) = (${x})² + ${a}(${x}) + ${b}.`,`The remainder is ${x*x+a*x+b}.`]};
  case 'composition':return {prompt:`f(x) = ${a}x + ${b}; g(x) = x². Find f(g(${x})).`,answer:a*x*x+b,hint:'Evaluate g first, then f.',steps:[`g(${x}) = ${x*x}.`,`f(${x*x}) = ${a}(${x*x}) + ${b} = ${a*x*x+b}.`]};
  case 'geometric-sequences':{const ratio=int(2,4),n=int(3,6);return {prompt:`A geometric sequence starts at ${a} and has ratio ${ratio}. Find term ${n}.`,answer:a*ratio**(n-1),hint:'Use a_n = a₁ × r^(n−1).',steps:[`a_${n} = ${a} × ${ratio}^${n-1}.`,`a_${n} = ${a*ratio**(n-1)}.`]};}
  case 'derivatives':{const n=int(2,4);return {prompt:`f(x) = ${a}x^${n}. Find f′(${x}).`,answer:a*n*x**(n-1),hint:'Apply the power rule before substituting the point.',steps:[`f′(x) = ${a*n}x^${n-1}.`,`f′(${x}) = ${a*n}(${x})^${n-1} = ${a*n*x**(n-1)}.`]};}
  default:throw new Error('Unknown secondary skill');
 }
}
