import {lessons,makeProblem} from './curriculum.mjs';
const e=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extra=[
 {id:'decimals',name:'Decimal operations',objective:'Add and subtract decimals using place value.',rule:'Line up the decimal points, add zeros if helpful, then calculate by place value.',steps:['Align decimal points.','Calculate from the smallest place value to the largest.','Keep the decimal point in the same column.'],examples:[{question:'2.35 + 1.4',work:['Write 1.4 as 1.40.','2.35 + 1.40 = 3.75.']},{question:'6.2 − 0.85',work:['Write 6.2 as 6.20.','6.20 − 0.85 = 5.35.']}],mistake:'Aligning the last digits instead of the decimal points puts different place values in the same column.'},
 {id:'integers',name:'Positive and negative numbers',objective:'Add signed integers and interpret their positions on a number line.',rule:'Adding a positive number moves right on a number line. Adding a negative number moves left.',steps:['Start at the first number.','Move right for a positive addend or left for a negative addend.','Read the position where you finish.'],examples:[{question:'−3 + 7',work:['Start at −3.','Move 7 units right to reach 4.']},{question:'5 + (−8)',work:['Start at 5.','Move 8 units left to reach −3.']}],mistake:'Two negative addends do not make a positive sum. That sign rule applies to multiplication, not addition.'},
 {id:'operations',name:'Order of operations',objective:'Evaluate expressions using a consistent order.',rule:'Evaluate parentheses first, then exponents, then multiplication/division from left to right, then addition/subtraction from left to right.',steps:['Evaluate expressions inside parentheses.','Perform multiplication and division.','Finish addition and subtraction.'],examples:[{question:'4 + 3 × 5',work:['Multiply first: 3 × 5 = 15.','Add: 4 + 15 = 19.']},{question:'(4 + 3) × 5',work:['Parentheses first: 4 + 3 = 7.','Multiply: 7 × 5 = 35.']}],mistake:'Do not calculate strictly left to right when operations have different priorities.'},
 {id:'coordinates',name:'Coordinates and distance',objective:'Find horizontal distance between points with the same y-coordinate.',rule:'An ordered pair (x, y) tells horizontal position first, then vertical position. Horizontal distance is the absolute difference between x-coordinates.',steps:['Check that the y-coordinates match.','Subtract the smaller x-coordinate from the larger.','Report a nonnegative distance in units.'],examples:[{question:'Distance from (−2, 3) to (4, 3)',work:['The y-coordinates are equal.','4 − (−2) = 6 units.']},{question:'Distance from (1, −1) to (7, −1)',work:['Both points are on y = −1.','7 − 1 = 6 units.']}],mistake:'Distance cannot be negative. Count the units between points rather than copying a coordinate.'},
 {id:'slope',name:'Slope of a line',objective:'Find slope from two points.',rule:'Slope is vertical change divided by horizontal change: m = (y₂ − y₁) / (x₂ − x₁). Use the same point order in both differences.',steps:['Subtract the y-coordinates.','Subtract the x-coordinates in the same order.','Divide vertical change by horizontal change.'],examples:[{question:'Slope through (1, 2) and (4, 8)',work:['Vertical change: 8 − 2 = 6.','Horizontal change: 4 − 1 = 3.','Slope: 6/3 = 2.']},{question:'Slope through (2, 7) and (6, 3)',work:['Vertical change: 3 − 7 = −4.','Horizontal change: 6 − 2 = 4.','Slope: −4/4 = −1.']}],mistake:'Rise/run is not run/rise. A vertical line has zero horizontal change and an undefined slope.'},
 {id:'probability',name:'Simple probability',objective:'Find the probability of an outcome in an equally likely sample space.',rule:'Probability = favorable outcomes ÷ total outcomes, when all individual outcomes are equally likely.',steps:['Count all possible equally likely outcomes.','Count the outcomes that match the event.','Write favorable/total and simplify.'],examples:[{question:'A bag has 3 red and 5 blue counters. Find P(red).',work:['There are 3 + 5 = 8 counters.','3 are red, so P(red) = 3/8.']},{question:'Find P(even) for a fair six-sided die.',work:['Even results are 2, 4, and 6: three outcomes.','P(even) = 3/6 = 1/2.']}],mistake:'The denominator includes every possible outcome, not only outcomes of the other color or type.'}
];
const order=['integers','decimals','fractions','percentages','ratios','operations','one-step','two-step','distribute','coordinates','slope','area','angles','pythagorean','probability'];
export const bookUnits=order.map(id=>[...lessons,...extra].find(lesson=>lesson.id===id));
const vocabulary={
 integers:[['Integer','A whole number, its negative, or zero.'],['Opposites','Numbers the same distance from zero in opposite directions.'],['Absolute value','A number’s distance from zero.']],
 decimals:[['Tenths','The first place to the right of the decimal point.'],['Hundredths','The second place to the right of the decimal point.'],['Equivalent decimals','Decimals with the same value, such as 1.4 and 1.40.']],
 fractions:[['Numerator','The number of selected equal parts.'],['Denominator','The total number of equal parts in a whole.'],['Equivalent fractions','Different fractions that describe the same value.']],
 percentages:[['Percent','An amount out of 100.'],['Whole','The original total amount.'],['Part','The amount described by a fraction or percent of the whole.']],
 ratios:[['Ratio','A multiplicative comparison of two quantities.'],['Unit rate','The amount per one unit.'],['Scale factor','The multiplier linking corresponding amounts.']],
 operations:[['Expression','Numbers and operations without an equals sign.'],['Parentheses','Symbols grouping an expression to evaluate first.'],['Evaluate','Calculate the value of an expression.']],
 'one-step':[['Variable','A symbol representing a number.'],['Inverse operations','Operations that undo one another.'],['Solution','A value that makes an equation true.']],
 'two-step':[['Coefficient','A factor multiplying a variable.'],['Constant','A fixed numerical term.'],['Isolate','Get the variable alone on one side.']],
 distribute:[['Distribute','Multiply an outside factor by every inside term.'],['Term','A part of an expression separated by addition or subtraction.'],['Equivalent expressions','Expressions with the same value for every permitted variable value.']],
 coordinates:[['Ordered pair','An (x, y) location on a coordinate plane.'],['x-axis','The horizontal axis.'],['y-axis','The vertical axis.']],
 slope:[['Rise','The vertical change between points.'],['Run','The horizontal change between points.'],['Slope','The ratio of rise to run.']],
 area:[['Base','The side used as the reference for a height.'],['Height','The perpendicular distance to a base.'],['Area','The amount of surface inside a figure, measured in square units.']],
 angles:[['Interior angle','An angle formed inside a polygon.'],['Right angle','An angle measuring 90°.'],['Triangle','A polygon with three sides and three interior angles.']],
 pythagorean:[['Legs','The two sides meeting at a right angle.'],['Hypotenuse','The side opposite the right angle.'],['Square root','A nonnegative number whose square equals a given nonnegative number.']],
 probability:[['Outcome','One possible result.'],['Event','A set of outcomes of interest.'],['Sample space','The set of all possible outcomes.']]
};
function randomSource(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
export function bookProblem(id,random){
 if(lessons.some(lesson=>lesson.id===id))return makeProblem(id,random);
 const int=(a,b)=>a+Math.floor(random()*(b-a+1)),a=int(2,12),b=int(2,12);
 switch(id){
  case 'integers':{const p=int(-15,15),q=int(-15,15);return {prompt:`${p} + (${q})`,answer:p+q,hint:q<0?'Move left for the second addend.':'Move right for the second addend.',steps:[`Start at ${p}; move ${Math.abs(q)} units ${q<0?'left':'right'}.`,`Finish at ${p+q}.`]};}
  case 'decimals':{const p=int(101,999),q=int(11,299);return {prompt:`${(p/100).toFixed(2)} + ${(q/100).toFixed(2)}`,answer:(p+q)/100,hint:'Align hundredths, tenths, and ones.',steps:['Align decimal points.',`The sum is ${((p+q)/100).toFixed(2)}.`]};}
  case 'operations':{const c=int(2,9);return {prompt:`${a} + ${b} × ${c}`,answer:a+b*c,hint:'Multiply before adding.',steps:[`${b} × ${c} = ${b*c}.`,`${a} + ${b*c} = ${a+b*c}.`]};}
  case 'coordinates':{const x=int(-8,2),d=int(2,12),y=int(-5,5);return {prompt:`Find the distance from (${x}, ${y}) to (${x+d}, ${y}).`,answer:d,hint:'Subtract the x-coordinates.',steps:[`The y-coordinates are equal.`,`${x+d} − (${x}) = ${d} units.`]};}
  case 'slope':{const x=int(-4,4),y=int(-4,4),run=int(1,5),rise=int(-8,8);return {prompt:`Find the slope through (${x}, ${y}) and (${x+run}, ${y+rise}).`,answer:rise/run,hint:'Use change in y divided by change in x.',steps:[`Rise = ${rise}; run = ${run}.`,`Slope = ${rise}/${run}.`]};}
  case 'probability':return {prompt:`A bag contains ${a} red and ${b} blue counters. Find P(red).`,answer:a/(a+b),hint:'Count all counters for the denominator.',steps:[`Total = ${a+b}.`,`P(red) = ${a}/${a+b}.`]};
 }
}
function application(id,n){
 const a=n+2,b=n+3;
 const data={
 integers:[`The temperature is −${a}°C. It rises ${b+4}°C. What is the new temperature?`,b+4-a,`−${a} + ${b+4} = ${b+4-a}°C.`],
 decimals:[`A notebook costs $${a}.25 and a pen costs $${b}.40. What is the total cost?`,a+b+.65,`${a}.25 + ${b}.40 = ${(a+b+.65).toFixed(2)}.`],
 fractions:[`You walk 1/${a} km before lunch and 1/${b} km after lunch. How far do you walk in total?`,1/a+1/b,`1/${a} + 1/${b} = ${a+b}/${a*b} km.`],
 percentages:[`A $${a*20} backpack is ${b*5}% off. What is the discount amount?`,a*20*b*5/100,`${b*5}/100 × ${a*20} = $${a*b}.`],
 ratios:[`${a} tickets cost $${a*b}. At the same price per ticket, what do ${a+4} tickets cost?`,(a+4)*b,`One ticket costs $${b}; ${a+4} tickets cost $${(a+4)*b}.`],
 operations:[`You have ${a} loose pencils and ${b} packs with 6 pencils in each. How many pencils do you have?`,a+b*6,`${a} + ${b} × 6 = ${a+b*6}.`],
 'one-step':[`After receiving ${a} stickers, you have ${a+b+5}. How many did you have at first?`,b+5,`x + ${a} = ${a+b+5}; x = ${b+5}.`],
 'two-step':[`A taxi charges a $${a} starting fee plus $${b} per km. The fare is $${a+b*4}. How many km was the trip?`,4,`${b}x + ${a} = ${a+b*4}; x = 4 km.`],
 distribute:[`${a} identical bags each contain x red and ${b} blue marbles. There are ${a*(b+6)} marbles altogether. Find x.`,6,`${a}(x + ${b}) = ${a*(b+6)}; x = 6.`],
 coordinates:[`On a map, a library is at (−${a}, 2) and a school is at (${b}, 2). Each grid unit is 1 km. How far apart are they?`,a+b,`${b} − (−${a}) = ${a+b} km.`],
 slope:[`A tank contains ${a*10} liters at minute 0 and ${a*10+b*5} liters at minute 5. Find its rate of change in liters per minute.`,b,`(${a*10+b*5} − ${a*10}) / 5 = ${b} liters per minute.`],
 area:[`A triangular garden has base ${a*2} m and perpendicular height ${b} m. What is its area?`,a*b,`A = ½ × ${a*2} × ${b} = ${a*b} m².`],
 angles:[`A triangular sign has two angles measuring ${a*10}° and ${b*10}°. What is its third angle?`,180-a*10-b*10,`180 − ${a*10} − ${b*10} = ${180-a*10-b*10}°.`],
 pythagorean:[`A rectangular field is ${a*3} m by ${a*4} m. How long is the straight diagonal across the field?`,a*5,`√(${a*3}² + ${a*4}²) = ${a*5} m.`],
 probability:[`A spinner has ${a+b} equal sections, ${a} of them green. What is the probability of landing on green?`,a/(a+b),`P(green) = ${a}/${a+b}.`]
 };
 const [prompt,answer,solution]=data[id];return {prompt,answer,steps:[solution]};
}
const svg=(content,label)=>`<svg class="model" viewBox="0 0 600 240" role="img" aria-label="${e(label)}" xmlns="http://www.w3.org/2000/svg"><g font-family="Arial" font-size="17" fill="#253d54">${content}</g></svg>`;
function blocks(count,filled,y,label){return `<text x="20" y="${y+23}">${label}</text>`+Array.from({length:count},(_,i)=>`<rect x="${120+i*420/count}" y="${y}" width="${420/count}" height="40" fill="${i<filled?'#8cb6d0':'#f4f7f9'}" stroke="#44667c"/>`).join('');}
export function visual(id){
 if(id==='fractions')return {caption:'Each strip is one whole split into 12 equal parts. Four parts plus three parts gives seven parts.',html:svg(blocks(12,4,25,'1/3')+blocks(12,3,95,'1/4')+blocks(12,7,165,'7/12'),'Fraction strips showing four twelfths plus three twelfths equals seven twelfths')};
 if(id==='percentages'||id==='probability')return {caption:id==='percentages'?'25 shaded squares out of 100 represent 25%, or one quarter.':'25 selected squares out of 100 equally likely squares give a probability of 25/100 = 1/4.',html:svg(Array.from({length:100},(_,i)=>`<rect x="${30+i%10*20}" y="${12+Math.floor(i/10)*20}" width="20" height="20" fill="${i<25?'#8cb6d0':'white'}" stroke="#56778e"/>`).join('')+'<text x="285" y="90">25 out of 100</text><text x="285" y="125">25/100 = 1/4</text><text x="285" y="160">One quarter of the grid</text>','Hundred square grid with twenty-five shaded squares')};
 if(id==='integers')return {caption:'Start at −3 and move seven units to the right. You finish at 4.',html:svg('<path d="M40 130H565" stroke="#304f67" stroke-width="2"/>'+Array.from({length:11},(_,i)=>`<path d="M${50+i*50} 123v14" stroke="#304f67"/><text x="${45+i*50}" y="160">${i-5}</text>`).join('')+'<path d="M150 115V65H500V115" fill="none" stroke="#2478a8" stroke-width="3"/><path d="m492 105 8 12 8-12" fill="none" stroke="#2478a8" stroke-width="3"/><text x="275" y="50">+7 units</text>','Number line from negative five to five showing a move from negative three to four')};
 if(['one-step','two-step','distribute'].includes(id))return {caption:'Each outlined x-block has the same value. Here 2x + 4 = 12. Remove four units from both sides, then split the remaining eight into two equal groups: x = 4.',html:svg('<rect x="40" y="50" width="70" height="45" fill="#dbeaf4" stroke="#44667c"/><rect x="120" y="50" width="70" height="45" fill="#dbeaf4" stroke="#44667c"/><text x="69" y="79">x</text><text x="149" y="79">x</text>'+Array.from({length:4},(_,i)=>`<rect x="${205+i*22}" y="61" width="19" height="22" fill="#ddd" stroke="#657789"/>`).join('')+'<text x="302" y="80">=</text>'+Array.from({length:12},(_,i)=>`<rect x="${335+i%6*25}" y="${50+Math.floor(i/6)*28}" width="21" height="23" fill="#ddd" stroke="#657789"/>`).join('')+'<text x="65" y="160">2x + 4 = 12</text><text x="65" y="197">2x = 8</text><text x="335" y="197">x = 4</text>','Algebra tiles showing two x tiles plus four unit tiles equals twelve unit tiles')};
 if(id==='area'||id==='pythagorean')return {caption:id==='area'?'The diagonal divides an 8-by-6 rectangle into two equal triangles. Each triangle has area 8 × 6 ÷ 2 = 24 square units.':'This right triangle has legs 8 and 6. Its hypotenuse is √(64 + 36) = 10.',html:svg('<rect x="120" y="35" width="240" height="150" fill="none" stroke="#9aaebc" stroke-dasharray="5 5"/><path d="M120 35V185H360Z" fill="#dceaf4" stroke="#365d78" stroke-width="2"/><path d="M120 166h19v19" fill="none" stroke="#365d78"/><text x="90" y="118">6</text><text x="235" y="215">8</text><text x="260" y="100">'+(id==='area'?'':'10')+'</text>','Right triangle inside a rectangle with base eight and height six')};
 if(id==='angles')return {caption:'The interior angles of this triangle are 45°, 65°, and 70°. Their sum is 180°.',html:svg('<path d="M85 200L285 30L480 200Z" fill="#edf3f7" stroke="#365d78" stroke-width="2"/><text x="140" y="185">45°</text><text x="385" y="185">65°</text><text x="264" y="92">70°</text><text x="215" y="235">45 + 65 + 70 = 180</text>','Schematic triangle labeled with angles forty-five, sixty-five, and seventy degrees; not drawn to scale')};
 if(id==='coordinates'||id==='slope')return {caption:id==='slope'?'From (1, 2) to (4, 8), the rise is 6 and the run is 3. Slope = 6/3 = 2.':'The horizontal coordinates change from 1 to 4: three units right. The vertical coordinates change from 2 to 8: six units up.',html:svg(Array.from({length:10},(_,i)=>`<path d="M${100+i*30} 15V205M100 ${25+i*20}H390" stroke="#e0e6eb"/>`).join('')+'<path d="M100 15V205H420" fill="none" stroke="#365d78"/><path d="M130 165L220 45" stroke="#2478a8" stroke-width="3"/><path d="M130 165H220V45" fill="none" stroke="#527d96" stroke-dasharray="4 3"/><circle cx="130" cy="165" r="4"/><circle cx="220" cy="45" r="4"/><text x="110" y="192">(1, 2)</text><text x="232" y="45">(4, 8)</text><text x="160" y="150">3</text><text x="234" y="110">6</text>','Coordinate diagram showing a rise of six and a run of three between two points')};
 if(id==='ratios')return {caption:'The same price appears in every column: $2 for one notebook. Scaling the number of notebooks scales the cost by the same factor.',html:svg('<rect x="60" y="45" width="480" height="130" fill="#f2f6f9" stroke="#658195"/><path d="M60 110H540M230 45V175M330 45V175M430 45V175" stroke="#658195"/><text x="80" y="85">Notebooks</text><text x="80" y="150">Cost ($)</text><text x="270" y="85">1</text><text x="370" y="85">3</text><text x="470" y="85">7</text><text x="270" y="150">2</text><text x="370" y="150">6</text><text x="470" y="150">14</text>','Ratio table showing one notebook costs two dollars, three cost six, and seven cost fourteen')};
 if(id==='decimals')return {caption:'Place-value blocks for 1.24: one whole, two tenths, and four hundredths. Ten hundredths have the same value as one tenth.',html:svg('<rect x="50" y="40" width="110" height="110" fill="#c3dbea" stroke="#44667c"/>'+Array.from({length:2},(_,i)=>`<rect x="${205+i*20}" y="40" width="11" height="110" fill="#8cb6d0" stroke="#44667c"/>`).join('')+Array.from({length:4},(_,i)=>`<rect x="${300+i*23}" y="139" width="11" height="11" fill="#567f9d"/>`).join('')+'<text x="57" y="190">1 whole</text><text x="185" y="190">2 tenths</text><text x="300" y="190">4 hundredths</text>','Decimal base-ten blocks representing one and twenty-four hundredths')};
 return {caption:'Multiplication combines equal groups. Three groups of five make fifteen. Add the four loose units afterward: 4 + 3 × 5 = 19.',html:svg(Array.from({length:3},(_,r)=>`<rect x="${180+r*115}" y="50" width="100" height="110" rx="3" fill="#edf3f7" stroke="#7893a6"/>`+Array.from({length:5},(_,i)=>`<rect x="${190+r*115+i%2*35}" y="${62+Math.floor(i/2)*29}" width="20" height="20" fill="#8cb6d0" stroke="#44667c"/>`).join('')).join('')+Array.from({length:4},(_,i)=>`<rect x="${35+i%2*34}" y="${78+Math.floor(i/2)*34}" width="22" height="22" fill="#ccd7df" stroke="#44667c"/>`).join('')+'<text x="45" y="200">4 +</text><text x="235" y="200">3 × 5 = 19</text>','Block model showing four individual units and three groups of five')};
}
export function textbookData(){
 return bookUnits.map((unit,index)=>{const random=randomSource(9217+index*817),questions=[],seen=new Set();for(let i=0;i<20;i++){let problem;for(let tries=0;tries<1000;tries++){problem=bookProblem(unit.id,random);if(!seen.has(problem.prompt))break;}seen.add(problem.prompt);questions.push(problem);}return {unit,index,guided:questions.slice(0,6),independent:questions.slice(6,14),review:questions.slice(14),applications:Array.from({length:4},(_,i)=>application(unit.id,i))};});
}
export function textbookHtml(){
 const pages=[];
 const list=items=>`<ol>${items.map(item=>`<li>${e(item)}</li>`).join('')}</ol>`;
 const exercises=(questions,start=1,hints=false)=>`<ol class="exercises" start="${start}">${questions.map(q=>`<li><p>${e(q.prompt)}</p>${hints?`<small>Start here: ${e(q.hint)}</small>`:''}<div class="work-lines"></div></li>`).join('')}</ol>`;
 for(const {unit,index,guided,independent,review,applications} of textbookData()){
  const number=String(index+1).padStart(2,'0'),model=visual(unit.id),all=[...guided,...independent,...applications,...review];
  const page=(title,body,kind='Lesson')=>{const n=pages.length+1;pages.push(`<section class="sheet" id="page-${n}"><header><span>STUDYREADY / MATHEMATICS</span><span>UNIT ${number} · ${e(kind)}</span></header><div class="page-body"><div class="unit-label">${e(unit.name)}</div><h1>${e(title)}</h1>${body}</div><footer><span>${e(unit.name)} · ${e(kind)}</span><span>${n} / 150</span></footer></section>`);};
  page(unit.name,`<p class="lead">${e(unit.objective)}</p><h2>Learning target</h2><p>${e(unit.rule)}</p><h2>Two-session lesson plan</h2><table><tr><th>Time</th><th>Session 1 · Learn and explain</th></tr><tr><td>5 min</td><td>Read the vocabulary. Recall a related example from an earlier lesson.</td></tr><tr><td>10 min</td><td>Teach the method on page ${index*10+2}; work through the examples on page ${index*10+3}.</td></tr><tr><td>10 min</td><td>Discuss the visual model on page ${index*10+4}. Explain what each part represents.</td></tr><tr><td>15 min</td><td>Complete guided practice, page ${index*10+5}. Compare methods with a partner.</td></tr><tr><td>5 min</td><td>Explain the rule in one sentence and write one question.</td></tr></table><table><tr><th>Time</th><th>Session 2 · Apply and check</th></tr><tr><td>15 min</td><td>Independent practice, page ${index*10+6}.</td></tr><tr><td>10 min</td><td>Applications, page ${index*10+7}.</td></tr><tr><td>10 min</td><td>Error discussion, page ${index*10+8}.</td></tr><tr><td>10 min</td><td>Review, page ${index*10+9}; check with the answer key on page ${index*10+10}.</td></tr></table><p class="note">Materials: pencil, paper, and a ruler for diagrams. Show your reasoning before using a calculator to check arithmetic.</p>`,'Teaching plan');
  page('Understand the method',`<div class="rule">${e(unit.rule)}</div><h2>Vocabulary</h2><dl>${vocabulary[unit.id].map(([term,definition])=>`<dt>${e(term)}</dt><dd>${e(definition)}</dd>`).join('')}</dl><h2>Steps to follow</h2>${list(unit.steps)}<h2>Check your understanding</h2><p>Explain why each step preserves the value or relationship in the problem. Use the first example on the next page to illustrate your explanation.</p><div class="writing"></div>`);
  page('Worked examples',unit.examples.map((example,i)=>`<article class="worked"><h2>Example ${i+1}</h2><p class="equation">${e(example.question)}</p>${list(example.work)}</article>`).join('')+`<div class="note"><strong>Compare the examples</strong><p>Which step is the same in both? Which numbers or conditions change?</p></div><h2>Your explanation</h2><div class="writing"></div>`);
  page('See the math',`${model.html}<p class="caption">${e(model.caption)}</p><h2>Read the model</h2><ol><li>Label the quantities represented in the diagram.</li><li>Write the calculation shown by the model.</li><li>Explain how the diagram supports the rule from page ${index*10+2}.</li></ol><h2>Build another example</h2><p>Change the quantities. Draw a new model, then solve the problem it represents.</p><div class="drawing-grid"></div>`,'Visual model');
  page('Guided practice',`<p>Use the hint to start. Show your work and include units when needed.</p>${exercises(guided,1,true)}`,'Practice');
  page('Independent practice',`<p>Work without the examples first. If you get stuck, identify the step you need before looking back.</p>${exercises(independent,7)}`,'Practice');
  page('Use it in context',`<p>Identify what is known and what you need to find. Write a calculation before answering.</p>${exercises(applications,15)}`,'Applications');
  page('Check the reasoning',`<h2>A common mistake</h2><div class="note">${e(unit.mistake)}</div><h2>A reliable method</h2><p class="equation">${e(unit.examples[0].question)}</p>${list(unit.examples[0].work)}<h2>Explain and correct</h2><ol><li>Describe how the common mistake would change this example.</li><li>Write the corrected calculation and explain the key step.</li><li>Create a second example that helps another student avoid this mistake.</li></ol><div class="writing large"></div><h2>Before you move on</h2><p>Check the size, sign, and units of your answer. Make sure they agree with the question.</p>`,'Reasoning');
  page('Unit review',`<p>Complete these without notes. Check your work with the next page, then revisit any step you missed.</p>${exercises(review,19)}<div class="note">Reflection: Which problem needed the most thought? Explain how you solved it.</div>`,'Review');
  page('Answers and checks',`<p class="small">Questions 1–6: guided · 7–14: independent · 15–18: applications · 19–24: review. Equivalent fractions and decimals are accepted.</p><ol class="answers">${all.map(q=>`<li>${q.steps.map(step=>e(step)).join(' ')}</li>`).join('')}</ol><div class="note small"><strong>Use the key to learn.</strong> If an answer differs, compare the steps and find the first place your work changed. Correct that step and solve the problem again.</div>`,'Answer key');
 }
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StudyReady Mathematics · 150-page textbook</title><link rel="stylesheet" href="/learning/textbook.css"></head><body><nav class="book-nav"><strong>StudyReady Mathematics</strong><a href="/textbook.pdf">Download PDF</a><details><summary>Units</summary>${bookUnits.map((u,i)=>`<a href="#page-${i*10+1}">${i+1}. ${e(u.name)}</a>`).join('')}</details><span>15 units · 150 pages</span></nav><main>${pages.join('')}</main></body></html>`;
}
