export function setupScreen({notice}){
 const button=document.getElementById('shareScreen'),panel=document.getElementById('screenPanel'),video=document.getElementById('screenPreview');let stream=null,opening=false,session=0;
 button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></svg>';
 function stop(){session++;stream?.getTracks().forEach(track=>track.stop());stream=null;video.srcObject=null;panel.hidden=true;button.setAttribute('aria-pressed','false');}
 button.onclick=async()=>{if(stream){stop();return;}if(opening)return;if(!navigator.mediaDevices?.getDisplayMedia){notice('Screen sharing is unavailable in this browser.');return;}opening=true;const current=++session;try{const selected=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:5},audio:false});if(current!==session){selected.getTracks().forEach(track=>track.stop());return;}stream=selected;video.srcObject=stream;await video.play();if(current!==session)return;panel.hidden=false;button.setAttribute('aria-pressed','true');stream.getVideoTracks()[0].addEventListener('ended',stop,{once:true});}catch(error){stop();if(error.name!=='NotAllowedError')notice('Could not start screen sharing.');}finally{opening=false;}};
 document.getElementById('stopScreen').onclick=stop;
 async function capture(){if(!stream)return null;if(video.readyState<2)throw Error('The shared screen is still loading. Try again.');const canvas=document.createElement('canvas'),scale=Math.min(1,1280/video.videoWidth);canvas.width=Math.max(1,Math.round(video.videoWidth*scale));canvas.height=Math.max(1,Math.round(video.videoHeight*scale));canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);let dataUrl;for(const quality of [.8,.6,.4,.25]){dataUrl=canvas.toDataURL('image/jpeg',quality);if(dataUrl.length<280000)return {dataUrl,screenCapture:true};}throw Error('The shared screen is too detailed. Share a smaller window.');}
 window.addEventListener('pagehide',stop);return {capture,stop};
}
